# Generated by Django 4.2.7 on 2025-08-29 15:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the property', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Property title/name', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed Use'), ('land', 'Land')], help_text='Type of property', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('tokenized', 'Tokenized'), ('under_construction', 'Under Construction'), ('sold_out', 'Sold Out'), ('closed', 'Closed'), ('delisted', 'Delisted')], default='draft', help_text='Current status of the property', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total property value in USD', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('token_price', models.DecimalField(decimal_places=2, help_text='Price per token in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_tokens', models.PositiveIntegerField(help_text='Total number of tokens for this property', validators=[django.core.validators.MinValueValidator(1)])),
                ('tokens_sold', models.PositiveIntegerField(default=0, help_text='Number of tokens already sold')),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, help_text='Expected annual return percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('rental_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Annual rental yield percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('property_size', models.DecimalField(blank=True, decimal_places=2, help_text='Property size in square feet', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('year_built', models.PositiveIntegerField(blank=True, help_text='Year the property was built', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('address', models.TextField(help_text='Full property address')),
                ('city', models.CharField(help_text='Property city', max_length=100)),
                ('state', models.CharField(blank=True, help_text='Property state/province', max_length=100, null=True)),
                ('country', models.CharField(help_text='Property country', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Property latitude coordinate', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Property longitude coordinate', max_digits=11, null=True)),
                ('smart_contract_address', models.CharField(blank=True, help_text='Blockchain smart contract address', max_length=255, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Whether property is featured')),
                ('minimum_investment', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum investment amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Property owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties_property',
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current appraised value', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valuation_date', models.DateTimeField(help_text='Date of valuation')),
                ('valuation_method', models.CharField(help_text='Method used for valuation', max_length=100)),
                ('appraiser', models.CharField(help_text='Name of appraiser or valuation company', max_length=255)),
                ('report', models.FileField(blank=True, help_text='Valuation report document', null=True, upload_to='valuation_reports/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the valuation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property being valued', on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Valuation',
                'verbose_name_plural': 'Property Valuations',
                'db_table': 'properties_property_valuation',
                'ordering': ['-valuation_date'],
                'indexes': [models.Index(fields=['property', 'valuation_date'], name='properties__propert_425d78_idx'), models.Index(fields=['valuation_date'], name='properties__valuati_a9cb3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Update title', max_length=255)),
                ('content', models.TextField(help_text='Update content')),
                ('update_type', models.CharField(choices=[('general', 'General'), ('financial', 'Financial'), ('construction', 'Construction'), ('legal', 'Legal')], help_text='Type of update', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Update',
                'verbose_name_plural': 'Property Updates',
                'db_table': 'properties_property_update',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'update_type'], name='properties__propert_cc06eb_idx'), models.Index(fields=['created_at'], name='properties__created_68efec_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property being subscribed to', on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(help_text='User subscribing to updates', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Subscription',
                'verbose_name_plural': 'Property Subscriptions',
                'db_table': 'properties_property_subscription',
                'indexes': [models.Index(fields=['user'], name='properties__user_id_d83ea7_idx'), models.Index(fields=['property'], name='properties__propert_22f825_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('review', models.TextField(help_text='Review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('user', models.ForeignKey(help_text='User writing the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Review',
                'verbose_name_plural': 'Property Reviews',
                'db_table': 'properties_property_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'rating'], name='properties__propert_4f746d_idx'), models.Index(fields=['created_at'], name='properties__created_ec385e_idx')],
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Property image file', upload_to='property_images/')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary property image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'properties_property_image',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['property', 'is_primary'], name='properties__propert_cdd291_idx'), models.Index(fields=['order'], name='properties__order_bd29ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name', max_length=255)),
                ('document', models.FileField(help_text='Document file', upload_to='property_documents/')),
                ('document_type', models.CharField(help_text='Type of document (e.g., legal, financial, technical)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'db_table': 'properties_property_document',
                'indexes': [models.Index(fields=['property', 'document_type'], name='properties__propert_fe8b96_idx'), models.Index(fields=['uploaded_at'], name='properties__uploade_96ae15_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'property_type'], name='properties__status_e02930_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'country'], name='properties__city_45e90f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured', 'status'], name='properties__feature_eedab8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner'], name='properties__owner_i_9e1ae3_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('tokens_sold__lte', models.F('total_tokens'))), name='tokens_sold_not_exceed_total'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('total_value__gt', 0)), name='total_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('token_price__gt', 0)), name='token_price_positive'),
        ),
    ]
