# Generated by Django 4.2.7 on 2024-09-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_tokenized',
            field=models.BooleanField(default=False, help_text='Whether property has been tokenized on blockchain'),
        ),
        migrations.AddField(
            model_name='property',
            name='tokenization_date',
            field=models.DateTimeField(blank=True, help_text='Date when property was tokenized', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='token_contract_address',
            field=models.CharField(blank=True, help_text='ERC-1155 token contract address', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distributor_contract_address',
            field=models.CharField(blank=True, help_text='Rental income distributor contract address', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='deployment_network',
            field=models.CharField(blank=True, help_text='Blockchain network where contracts are deployed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='token_lockup_period_days',
            field=models.PositiveIntegerField(default=365, help_text='Token lockup period in days'),
        ),
        migrations.AddField(
            model_name='property',
            name='early_exit_fee_rate',
            field=models.PositiveIntegerField(default=1000, help_text='Early exit fee rate in basis points (10% = 1000)'),
        ),
        migrations.AddField(
            model_name='property',
            name='platform_fee_rate',
            field=models.PositiveIntegerField(default=250, help_text='Platform fee rate in basis points (2.5% = 250)'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_distribution_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', help_text='How often rental income is distributed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_rental_distribution',
            field=models.DateTimeField(blank=True, help_text='Date of last rental income distribution', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rental_distributed',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Total rental income distributed to investors', max_digits=20),
        ),
        migrations.AddField(
            model_name='property',
            name='blockchain_metadata',
            field=models.JSONField(default=dict, help_text='Additional blockchain-specific metadata'),
        ),
    ]