# Generated by Django 4.2.7 on 2025-08-30 12:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, help_text='Total number of property page views')),
                ('unique_views', models.PositiveIntegerField(default=0, help_text='Number of unique visitors to property page')),
                ('total_subscriptions', models.PositiveIntegerField(default=0, help_text='Total number of subscriptions to property updates')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Conversion rate from views to investments', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('average_investment_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average investment amount for this property', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('funding_velocity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tokens sold per day (funding velocity)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('roi_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Actual ROI achieved', max_digits=10, null=True)),
                ('market_performance_score', models.DecimalField(blank=True, decimal_places=2, help_text='Market performance score (0-10)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(help_text='Property these analytics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Analytics',
                'verbose_name_plural': 'Property Analytics',
                'db_table': 'properties_property_analytics',
            },
        ),
        migrations.CreateModel(
            name='PropertyViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the viewer')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='properties.property')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the property (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property View Log',
                'verbose_name_plural': 'Property View Logs',
                'db_table': 'properties_property_view_log',
                'indexes': [models.Index(fields=['property', 'viewed_at'], name='properties__propert_397da2_idx'), models.Index(fields=['user', 'viewed_at'], name='properties__user_id_402601_idx'), models.Index(fields=['ip_address', 'viewed_at'], name='properties__ip_addr_bfea74_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparable_sales_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Average price of comparable sales', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('market_appreciation_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual market appreciation rate', max_digits=5, null=True)),
                ('rental_market_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Market rental rate per month', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vacancy_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Local vacancy rate percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Price per square foot', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('neighborhood_score', models.DecimalField(blank=True, decimal_places=1, help_text='Neighborhood desirability score (0-10)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('data_source', models.CharField(help_text='Source of the market data', max_length=255)),
                ('data_date', models.DateField(help_text='Date of the market data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Property this market data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Market Data',
                'verbose_name_plural': 'Property Market Data',
                'db_table': 'properties_property_market_data',
                'ordering': ['-data_date'],
                'indexes': [models.Index(fields=['property', 'data_date'], name='properties__propert_031086_idx'), models.Index(fields=['data_date'], name='properties__data_da_b12045_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], default='pending', help_text='Current approval status', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('required_changes', models.TextField(blank=True, help_text='Changes required before approval')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the property was submitted for approval')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the property was reviewed', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the property was approved', null=True)),
                ('property', models.OneToOneField(help_text='Property being reviewed for approval', on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='properties.property')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Admin user reviewing the property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Approval',
                'verbose_name_plural': 'Property Approvals',
                'db_table': 'properties_property_approval',
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='properties__status_a6e352_idx'), models.Index(fields=['reviewer'], name='properties__reviewe_aad776_idx')],
            },
        ),
    ]
