# Generated by Django 4.2.7 on 2025-09-12 09:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyanalytics_propertyviewlog_propertymarketdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='construction_progress',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Construction completion percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='property',
            name='expected_completion_date',
            field=models.DateField(blank=True, help_text='Expected completion date for construction properties', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='installment_period_months',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum installment period in months', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rental_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current monthly rental income', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Current occupancy rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('ready_property', 'Ready Property')], default='ready_property', help_text='Investment category - construction vs ready property', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_income_active',
            field=models.BooleanField(default=False, help_text='Whether property is actively generating rental income'),
        ),
        migrations.AddField(
            model_name='property',
            name='supports_installments',
            field=models.BooleanField(default=False, help_text='Whether property supports installment payments'),
        ),
    ]
