# Generated by Django 4.2.7 on 2025-09-12 09:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_construction_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalIncomeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_period', models.CharField(help_text='Distribution period in YYYY-MM format', max_length=7)),
                ('total_rental_income', models.DecimalField(decimal_places=2, help_text='Total rental income collected for the period', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform management fee deducted', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_distribution_amount', models.DecimalField(decimal_places=2, help_text='Net amount distributed to token holders', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tokens_eligible', models.PositiveIntegerField(help_text='Number of tokens eligible for distribution')),
                ('amount_per_token', models.DecimalField(decimal_places=8, help_text='Distribution amount per token', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('distribution_date', models.DateTimeField(auto_now_add=True, help_text='Date when distribution was processed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the distribution')),
                ('property', models.ForeignKey(help_text='Property generating the rental income', on_delete=django.db.models.deletion.CASCADE, related_name='rental_distributions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rental Income Distribution',
                'verbose_name_plural': 'Rental Income Distributions',
                'db_table': 'properties_rental_income_distribution',
                'ordering': ['-distribution_period'],
                'indexes': [models.Index(fields=['property', 'distribution_period'], name='properties__propert_3f4ed0_idx'), models.Index(fields=['distribution_date'], name='properties__distrib_d93735_idx')],
                'unique_together': {('property', 'distribution_period')},
            },
        ),
    ]
