# Generated by Django 4.2.7 on 2025-09-12 12:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_rentalincomedistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the installment payment', primary_key=True, serialize=False)),
                ('total_investment_amount', models.DecimalField(decimal_places=2, help_text='Total amount to be invested over time', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('token_allocation', models.PositiveIntegerField(help_text='Number of tokens allocated for this installment plan', validators=[django.core.validators.MinValueValidator(1)])),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Amount per installment payment', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_installments', models.PositiveIntegerField(help_text='Total number of installment payments', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', help_text='Payment frequency', max_length=20)),
                ('payments_made', models.PositiveIntegerField(default=0, help_text='Number of payments successfully made')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tokens_released', models.PositiveIntegerField(default=0, help_text='Number of tokens released to investor')),
                ('next_payment_date', models.DateField(help_text='Date of next scheduled payment')),
                ('completion_date', models.DateField(blank=True, help_text='Expected or actual completion date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the installment plan', max_length=20)),
                ('graduated_release', models.BooleanField(default=True, help_text='Whether tokens are released gradually with each payment')),
                ('tokens_per_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Tokens released per successful payment (can be fractional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('early_completion_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage for early completion', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('25.00'))])),
                ('late_payment_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for late payments', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grace_period_days', models.PositiveIntegerField(default=7, help_text='Grace period for payments before late fees apply', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the installment plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(help_text='Investor making the installment payments', on_delete=django.db.models.deletion.CASCADE, related_name='property_installments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='Property for which installment is being paid', on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='properties.property')),
            ],
            options={
                'verbose_name': 'Installment Payment',
                'verbose_name_plural': 'Installment Payments',
                'db_table': 'properties_installment_payment',
                'indexes': [models.Index(fields=['property', 'investor'], name='properties__propert_2f92c8_idx'), models.Index(fields=['status', 'next_payment_date'], name='properties__status_ce0ddd_idx'), models.Index(fields=['investor', 'status'], name='properties__investo_7554eb_idx'), models.Index(fields=['next_payment_date'], name='properties__next_pa_3320eb_idx'), models.Index(fields=['created_at'], name='properties__created_7eb668_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='installmentpayment',
            constraint=models.CheckConstraint(check=models.Q(('total_amount_paid__lte', models.F('total_investment_amount'))), name='installment_paid_not_exceed_total'),
        ),
        migrations.AddConstraint(
            model_name='installmentpayment',
            constraint=models.CheckConstraint(check=models.Q(('payments_made__lte', models.F('total_installments'))), name='installment_payments_not_exceed_total'),
        ),
        migrations.AddConstraint(
            model_name='installmentpayment',
            constraint=models.CheckConstraint(check=models.Q(('tokens_released__lte', models.F('token_allocation'))), name='installment_tokens_not_exceed_allocation'),
        ),
    ]
