# Generated by Django 4.2.7 on 2025-09-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_installmentpayment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='installmentpayment',
            name='properties__propert_2f92c8_idx',
        ),
        migrations.RemoveField(
            model_name='installmentpayment',
            name='property',
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='property_investment',
            field=models.ForeignKey(help_text='Property for which installment is being paid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['property_investment', 'investor'], name='properties__propert_1f9894_idx'),
        ),
    ]
