# Generated by Django 4.2.7 on 2025-09-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_blockchain_fields'),
        ('properties', '0006_remove_installmentpayment_properties__propert_2f92c8_idx_and_more'),
    ]

    operations = [
    ]
