# Generated by Django 4.2.7 on 2025-09-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_merge_20250913_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='blockchain_metadata',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deployment_network',
        ),
        migrations.RemoveField(
            model_name='property',
            name='distributor_contract_address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='early_exit_fee_rate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_tokenized',
        ),
        migrations.RemoveField(
            model_name='property',
            name='last_rental_distribution',
        ),
        migrations.RemoveField(
            model_name='property',
            name='platform_fee_rate',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rental_distribution_frequency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='token_contract_address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='token_lockup_period_days',
        ),
        migrations.RemoveField(
            model_name='property',
            name='tokenization_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_rental_distributed',
        ),
    ]
