# Generated by Django 5.2.8 on 2026-01-31 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_blockchain_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertydocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Property Document', 'verbose_name_plural': 'Property Documents'},
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='investor_access',
            field=models.BooleanField(default=True, help_text='Whether verified investors can access this document'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='is_latest',
            field=models.BooleanField(default=True, help_text='Whether this is the latest version of the document'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this document is publicly accessible'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Document version number'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='document_type',
            field=models.CharField(choices=[('ownership', 'Ownership & Title'), ('valuation', 'Valuation Report'), ('insurance', 'Insurance Policy'), ('spv', 'SPV Documents'), ('management', 'Property Management'), ('financial', 'Financial Report'), ('legal', 'Legal Documents'), ('technical', 'Technical Documents'), ('other', 'Other')], default='other', help_text='Type of document (ownership, valuation, insurance, spv, management, financial, other)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['property', 'name', 'is_latest'], name='properties__propert_e4c431_idx'),
        ),
    ]
