# Generated by Django 6.0.5 on 2026-05-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
        ('properties', '0011_add_spv_fields_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lockup_months',
            field=models.PositiveIntegerField(default=12, help_text='Lockup period from mint date before tokens may be transferred.'),
        ),
        migrations.AddField(
            model_name='property',
            name='offering_type',
            field=models.CharField(choices=[('reg_d', 'Reg D (Accredited US Investors)'), ('reg_cf', 'Reg CF (Crowdfunding)'), ('reg_a', 'Reg A (Mini-IPO)'), ('reg_s', 'Reg S (Non-US Investors)'), ('private', 'Private Placement')], default='private', help_text='Securities offering exemption / structure used for this property.', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='requires_accredited_investors',
            field=models.BooleanField(default=False, help_text='If True, only investors flagged as accredited may participate.'),
        ),
        migrations.AddField(
            model_name='property',
            name='spv_entity',
            field=models.ForeignKey(blank=True, help_text='The Special Purpose Vehicle that legally owns this property.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='legal.legalentity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='spv_bank_account_number',
            field=models.CharField(blank=True, help_text='DEPRECATED — use spv_entity.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='spv_bank_name',
            field=models.CharField(blank=True, help_text='DEPRECATED — use spv_entity.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='spv_company_name',
            field=models.CharField(blank=True, help_text='DEPRECATED — use spv_entity. Free-text SPV company name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='spv_establishment_date',
            field=models.DateField(blank=True, help_text='DEPRECATED — use spv_entity.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='spv_registration_number',
            field=models.CharField(blank=True, help_text='DEPRECATED — use spv_entity.', max_length=100, null=True),
        ),
    ]
