# Generated by Django 4.2.7 on 2025-08-30 12:44

import broker.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the broker profile', primary_key=True, serialize=False)),
                ('license_number', models.CharField(help_text='Broker license number', max_length=50, unique=True)),
                ('license_state', models.CharField(help_text='State/province where license is valid', max_length=50)),
                ('license_expiry', models.DateField(help_text='License expiration date')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Broker verification status', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Commission rate percentage (0.01-10.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))])),
                ('referral_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Referral commission rate percentage (0.01-5.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('company_name', models.CharField(blank=True, help_text="Broker's company name", max_length=200, null=True)),
                ('company_address', models.TextField(blank=True, help_text='Company address', null=True)),
                ('website', models.URLField(blank=True, help_text="Broker's website URL", null=True)),
                ('bio', models.TextField(blank=True, help_text='Professional biography', null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience in real estate')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of specialization areas')),
                ('languages_spoken', models.JSONField(blank=True, default=list, help_text='List of languages spoken')),
                ('profile_image', models.ImageField(blank=True, help_text='Broker profile image', null=True, upload_to='broker_profiles/')),
                ('is_premium', models.BooleanField(default=False, help_text='Whether broker has premium features')),
                ('premium_expires_at', models.DateTimeField(blank=True, help_text='Premium subscription expiry date', null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales amount', max_digits=15)),
                ('total_commissions_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commissions earned', max_digits=12)),
                ('active_referrals_count', models.PositiveIntegerField(default=0, help_text='Number of active referrals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Profile',
                'verbose_name_plural': 'Broker Profiles',
                'db_table': 'broker_profile',
            },
        ),
        migrations.CreateModel(
            name='BrokerReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the referral', primary_key=True, serialize=False)),
                ('referral_code', models.CharField(default=broker.models.generate_referral_code, help_text='Unique referral code', max_length=20, unique=True)),
                ('referred_email', models.EmailField(blank=True, help_text='Email of referred prospect (before registration)', max_length=254, null=True)),
                ('is_converted', models.BooleanField(default=False, help_text='Whether referral resulted in successful conversion')),
                ('conversion_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invested by referred user', max_digits=15)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commission earned from this referral', max_digits=12)),
                ('first_investment_at', models.DateTimeField(blank=True, help_text='When referred user made first investment', null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last activity from this referral')),
                ('is_active', models.BooleanField(default=True, help_text='Whether referral code is active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Referral code expiration date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the referral', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='Broker making the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='broker.brokerprofile')),
                ('referred_user', models.ForeignKey(blank=True, help_text='User who was referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Referral',
                'verbose_name_plural': 'Broker Referrals',
                'db_table': 'broker_referral',
            },
        ),
        migrations.CreateModel(
            name='BrokerPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the metrics record', primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Month these metrics are for (first day of month)')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales amount for the month', max_digits=15)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commissions earned for the month', max_digits=12)),
                ('investment_count', models.PositiveIntegerField(default=0, help_text='Number of investments facilitated')),
                ('new_referrals', models.PositiveIntegerField(default=0, help_text='New referrals generated this month')),
                ('converted_referrals', models.PositiveIntegerField(default=0, help_text='Referrals that converted to investors')),
                ('referral_conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Referral conversion rate percentage', max_digits=5)),
                ('avg_investment_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average investment size facilitated', max_digits=12)),
                ('unique_investors', models.PositiveIntegerField(default=0, help_text='Number of unique investors served')),
                ('repeat_investors', models.PositiveIntegerField(default=0, help_text='Number of repeat investors')),
                ('client_retention_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Client retention rate percentage', max_digits=5)),
                ('marketing_materials_downloaded', models.PositiveIntegerField(default=0, help_text='Marketing materials downloaded this month')),
                ('performance_rank', models.PositiveIntegerField(blank=True, help_text='Performance rank among all brokers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='Broker these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='broker.brokerprofile')),
            ],
            options={
                'verbose_name': 'Broker Performance Metrics',
                'verbose_name_plural': 'Broker Performance Metrics',
                'db_table': 'broker_performance_metrics',
            },
        ),
        migrations.CreateModel(
            name='BrokerCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the commission', primary_key=True, serialize=False)),
                ('commission_type', models.CharField(choices=[('investment', 'Investment Commission'), ('referral', 'Referral Commission'), ('performance', 'Performance Bonus'), ('direct_sales', 'Direct Sales')], default='investment', help_text='Type of commission', max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base amount for commission calculation', max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate applied', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount earned', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', help_text='Commission status', max_length=20)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When commission was earned')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When commission was approved', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When commission was paid', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the commission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(help_text='Broker earning the commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='broker.brokerprofile')),
                ('investment', models.ForeignKey(blank=True, help_text='Related investment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_commissions', to='investments.investment')),
                ('referral', models.ForeignKey(blank=True, help_text='Related referral (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='broker.brokerreferral')),
            ],
            options={
                'verbose_name': 'Broker Commission',
                'verbose_name_plural': 'Broker Commissions',
                'db_table': 'broker_commission',
            },
        ),
        migrations.CreateModel(
            name='MarketingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the material', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Material title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Material description', null=True)),
                ('material_type', models.CharField(choices=[('brochure', 'Brochure'), ('presentation', 'Presentation'), ('flyer', 'Flyer'), ('video', 'Video'), ('infographic', 'Infographic'), ('report', 'Report'), ('logo', 'Logo'), ('banner', 'Banner')], help_text='Type of marketing material', max_length=20)),
                ('file', models.FileField(help_text='Marketing material file', upload_to='marketing_materials/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Material thumbnail image', null=True, upload_to='marketing_materials/thumbnails/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(help_text='File format (PDF, PNG, etc.)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether material is available for download')),
                ('is_premium_only', models.BooleanField(default=False, help_text='Whether material is only for premium brokers')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('version', models.CharField(default='1.0', help_text='Material version', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing materials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Material',
                'verbose_name_plural': 'Marketing Materials',
                'db_table': 'marketing_material',
                'indexes': [models.Index(fields=['material_type', 'is_active'], name='marketing_m_materia_e58f06_idx'), models.Index(fields=['is_premium_only'], name='marketing_m_is_prem_dd2bf3_idx'), models.Index(fields=['created_at'], name='marketing_m_created_ca0341_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='brokerreferral',
            index=models.Index(fields=['referral_code'], name='broker_refe_referra_09e86a_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerreferral',
            index=models.Index(fields=['broker', 'is_converted'], name='broker_refe_broker__ab2cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerreferral',
            index=models.Index(fields=['is_active', 'expires_at'], name='broker_refe_is_acti_0d8d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerreferral',
            index=models.Index(fields=['created_at'], name='broker_refe_created_194508_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['verification_status'], name='broker_prof_verific_ba7c63_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['license_number'], name='broker_prof_license_451e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['is_premium'], name='broker_prof_is_prem_ddcfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['created_at'], name='broker_prof_created_aaf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerperformancemetrics',
            index=models.Index(fields=['broker', 'month'], name='broker_perf_broker__fe242f_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerperformancemetrics',
            index=models.Index(fields=['month', 'total_sales'], name='broker_perf_month_45266f_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerperformancemetrics',
            index=models.Index(fields=['performance_rank'], name='broker_perf_perform_bf5d87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brokerperformancemetrics',
            unique_together={('broker', 'month')},
        ),
        migrations.AddIndex(
            model_name='brokercommission',
            index=models.Index(fields=['broker', 'status'], name='broker_comm_broker__4dfa16_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercommission',
            index=models.Index(fields=['commission_type'], name='broker_comm_commiss_eb266c_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercommission',
            index=models.Index(fields=['earned_at'], name='broker_comm_earned__7ac7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercommission',
            index=models.Index(fields=['status', 'earned_at'], name='broker_comm_status_49fd10_idx'),
        ),
    ]
