# Generated by Django 5.1.4 on 2025-09-23 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the application', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Applicant's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Applicant's last name", max_length=100)),
                ('email', models.EmailField(help_text="Applicant's email address", max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text="Applicant's phone number", max_length=20)),
                ('country', models.CharField(help_text='Country of residence', max_length=100)),
                ('city_address', models.TextField(help_text='City and address')),
                ('license_number', models.CharField(blank=True, help_text='Real estate license number (optional)', max_length=50, null=True)),
                ('experience_level', models.CharField(choices=[('0-1', '0-1 Years'), ('2-5', '2-5 Years'), ('5-10', '5-10 Years'), ('10+', '10+ Years')], help_text='Years of experience', max_length=10)),
                ('current_company', models.CharField(blank=True, help_text='Current brokerage/company name (optional)', max_length=200, null=True)),
                ('referral_strategy', models.TextField(help_text='How they plan to refer clients')),
                ('supporting_documents', models.FileField(blank=True, help_text='Supporting documents (license, company registration, etc.)', null=True, upload_to='broker_applications/documents/')),
                ('terms_accepted', models.BooleanField(default=False, help_text='Broker Program Terms & Conditions accepted')),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', help_text='Application review status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_user', models.OneToOneField(blank=True, help_text='User account created after approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_application', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_broker_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Application',
                'verbose_name_plural': 'Broker Applications',
                'db_table': 'broker_application',
                'indexes': [models.Index(fields=['application_status'], name='broker_appl_applica_df75b5_idx'), models.Index(fields=['email'], name='broker_appl_email_b66f36_idx'), models.Index(fields=['created_at'], name='broker_appl_created_5b1c3c_idx'), models.Index(fields=['application_status', 'created_at'], name='broker_appl_applica_ddec4d_idx')],
            },
        ),
    ]
