/**
 * Verification Center — a gateway page (client request).
 *
 * Capimax RT does NOT run its own verification system. Instead this page is a
 * unified "Verification Center" that hands the user off to the ecosystem's
 * central verification platform, Capimax Trust (https://www.capimax.pro), where
 * every document / certificate / record issued through the platform — or by
 * external parties (valuation firms, insurers, legal advisors, auditors,
 * financial institutions, government authorities) — can be verified, its status
 * reviewed, and an official copy downloaded.
 *
 * Bilingual (EN/AR) — follows the app's current i18n language + RTL direction.
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { ShieldCheck, ExternalLink, BadgeCheck } from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { Footer } from '../components/layout/Footer';
import CapimaxTrustLogo from '../assets/capimax-trust-logo.png';

const TRUST_URL = 'https://www.capimax.pro';

const COPY = {
  en: {
    title: 'Verification Center',
    body:
      'All documents, certificates, and records issued through this platform — including those generated by the Capimax ecosystem as well as documents issued by external organizations such as valuation firms, insurance providers, legal advisors, auditors, financial institutions, and government authorities — can be verified, their status reviewed, and official copies downloaded through the Capimax Trust platform.',
    body2:
      'Capimax Trust serves as the central verification gateway for the Capimax ecosystem, providing a secure and trusted source for validating the authenticity and integrity of registered documents.',
    features: [
      'Verify the authenticity of documents',
      'Review a document’s current status',
      'Download the official copy',
      'View the document’s verification data',
    ],
    cta: 'Go to Capimax Trust',
    ctaHint: 'Click here to verify',
    verifyBtn: 'Verify Documents',
    poweredBy: 'Central verification by Capimax Trust',
  },
  ar: {
    title: 'مركز التحقق',
    body:
      'جميع المستندات والشهادات والسجلات الصادرة من هذه المنصة، سواء كانت صادرة من منظومة Capimax أو من جهات خارجية مثل شركات التقييم، وشركات التأمين، والمكاتب القانونية، والمدققين، والمؤسسات المالية، والجهات الحكومية، يمكن التحقق منها، واستعراض حالتها، وتحميل النسخة الرسمية منها من خلال منصة Capimax Trust.',
    body2:
      'تعمل Capimax Trust كبوابة التحقق المركزية لمنظومة Capimax، وتوفّر مصدرًا آمنًا وموثوقًا للتحقق من صحة وسلامة المستندات المسجّلة.',
    features: [
      'التحقق من صحة المستندات',
      'عرض حالة المستند',
      'تحميل النسخة الرسمية',
      'الاطلاع على بيانات التحقق الخاصة بالمستند',
    ],
    cta: 'الانتقال إلى Capimax Trust',
    ctaHint: 'اضغط هنا للتحقق',
    verifyBtn: 'التحقق من المستندات',
    poweredBy: 'التحقق المركزي عبر Capimax Trust',
  },
};

export const VerificationCenterPage: React.FC = () => {
  const { i18n } = useTranslation();
  const isAr = (i18n.language || 'en').toLowerCase().startsWith('ar');
  const t = isAr ? COPY.ar : COPY.en;

  return (
    <div
      dir={isAr ? 'rtl' : 'ltr'}
      className="min-h-screen bg-gradient-to-br from-slate-50 via-emerald-50/30 to-slate-50 dark:from-slate-900 dark:via-slate-900 dark:to-slate-800"
    >
      <Navbar />

      <main className="relative pt-16">
        <section className="relative overflow-hidden">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-24 text-center">
            {/* Big Capimax Trust logo — flex-centered (a plain inline-block +
               text-center was rendering off-centre) on a white plate so it
               reads on any theme. */}
            <div className="flex justify-center mb-8">
              <div className="rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 px-6 py-4">
                <img
                  src={CapimaxTrustLogo}
                  alt="Capimax Trust"
                  className="h-24 sm:h-32 w-auto"
                />
              </div>
            </div>

            {/* Verified badge + title */}
            <div className="inline-flex items-center gap-2 rounded-full bg-emerald-100 dark:bg-emerald-900/30 px-4 py-1.5 mb-5">
              <ShieldCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
              <span className="text-sm font-semibold text-emerald-700 dark:text-emerald-300">
                {t.poweredBy}
              </span>
            </div>

            <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-6">
              {t.title}
            </h1>

            <p className="text-base sm:text-lg text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
              {t.body}
            </p>
            <p className="text-sm sm:text-base text-slate-500 dark:text-slate-400 leading-relaxed mb-8">
              {t.body2}
            </p>

            {/* What you can do */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-xl mx-auto mb-10 text-start">
              {t.features.map((f) => (
                <div
                  key={f}
                  className="flex items-center gap-2.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-white/70 dark:bg-slate-800/50 px-3.5 py-2.5"
                >
                  <BadgeCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                  <span className="text-sm text-slate-700 dark:text-slate-200">{f}</span>
                </div>
              ))}
            </div>

            {/* Capimax Trust brand + CTA */}
            <div className="rounded-2xl border border-emerald-200 dark:border-emerald-800 bg-white dark:bg-slate-800/60 p-6 sm:p-8">
              <div className="flex items-center justify-center gap-2 mb-1.5">
                <ShieldCheck className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">
                  {isAr ? 'بوابة التحقق المركزية' : 'Central Verification Gateway'}
                </span>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 mb-5">
                www.capimax.pro
              </p>

              <a
                href={TRUST_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-semibold px-6 py-3 text-base transition-colors shadow-lg shadow-emerald-600/20"
              >
                {t.cta}
                <ExternalLink className="w-4 h-4" />
              </a>

              <div className="mt-3">
                <a
                  href={TRUST_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm font-medium text-emerald-700 dark:text-emerald-400 hover:underline"
                >
                  {t.ctaHint} →
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default VerificationCenterPage;
