# Generated by Django 4.2.7 on 2025-08-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kyc.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', help_text='Current KYC verification status', max_length=20)),
                ('verification_level', models.CharField(choices=[('basic', 'Basic'), ('enhanced', 'Enhanced'), ('premium', 'Premium')], default='basic', help_text='Level of KYC verification completed', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when KYC was first submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when KYC was last reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for KYC rejection')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes about the KYC review')),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='Automated risk score (0-100, higher = higher risk)')),
                ('investment_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum investment amount allowed based on KYC level', max_digits=12, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When KYC verification expires (for renewal)', null=True)),
                ('last_updated_documents', models.DateTimeField(blank=True, help_text='Last time documents were updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin user who reviewed this KYC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User associated with this KYC profile', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
                'db_table': 'kyc_profile',
            },
        ),
        migrations.CreateModel(
            name='KYCNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Content of the note')),
                ('is_internal', models.BooleanField(default=True, help_text='Whether this note is for internal use only')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('review', 'Review'), ('rejection', 'Rejection'), ('approval', 'Approval'), ('follow_up', 'Follow Up')], default='general', help_text='Type of note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='User who created this note', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kyc_profile', models.ForeignKey(help_text='KYC profile this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='kyc.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Note',
                'verbose_name_plural': 'KYC Notes',
                'db_table': 'kyc_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the document', primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie'), ('video_verification', 'Video Verification')], help_text='Type of document uploaded', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('resubmission_required', 'Resubmission Required')], default='pending', help_text='Current verification status of this document', max_length=30)),
                ('file_path', models.FileField(help_text='Path to the uploaded document file', upload_to=kyc.models.kyc_document_upload_path)),
                ('file_name', models.CharField(help_text='Original filename of uploaded document', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash of the file for integrity verification', max_length=64)),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiration date (for ID documents)', null=True)),
                ('document_number', models.CharField(blank=True, help_text='Document number (passport, ID number, etc.)', max_length=100)),
                ('country_of_issue', models.CharField(blank=True, help_text='Country that issued the document', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when document was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for document rejection')),
                ('ocr_data', models.JSONField(blank=True, default=dict, help_text='OCR extracted data from the document')),
                ('verification_checks', models.JSONField(blank=True, default=dict, help_text='Results from third-party verification services')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_profile', models.ForeignKey(help_text='KYC profile this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin user who reviewed this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_document',
            },
        ),
        migrations.CreateModel(
            name='KYCAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action that was performed', max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Details of the action performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the browser/client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kyc_profile', models.ForeignKey(help_text='KYC profile this audit log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='kyc.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Audit Log',
                'verbose_name_plural': 'KYC Audit Logs',
                'db_table': 'kyc_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('aml', 'AML Screening'), ('sanctions', 'Sanctions Check'), ('pep', 'PEP Screening'), ('adverse_media', 'Adverse Media'), ('watchlist', 'Watchlist Check')], help_text='Type of compliance check', max_length=50)),
                ('result', models.CharField(choices=[('clear', 'Clear'), ('hit', 'Hit'), ('inconclusive', 'Inconclusive'), ('error', 'Error')], help_text='Result of the compliance check', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score of the result (0-100)', max_digits=5, null=True)),
                ('provider', models.CharField(help_text='Compliance screening provider', max_length=100)),
                ('reference_id', models.CharField(blank=True, help_text='External reference ID from provider', max_length=255)),
                ('raw_response', models.JSONField(default=dict, help_text='Raw response from compliance provider')),
                ('hits_data', models.JSONField(default=list, help_text='Details of any hits found during screening')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this compliance check was reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Review notes for compliance check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this compliance check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User being screened', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'verbose_name_plural': 'Compliance Checks',
                'db_table': 'kyc_compliance_check',
            },
        ),
        migrations.CreateModel(
            name='BiometricVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveness_score', models.DecimalField(blank=True, decimal_places=2, help_text='Liveness detection score (0-100)', max_digits=5, null=True)),
                ('face_match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Face matching score with ID document (0-100)', max_digits=5, null=True)),
                ('verification_session_id', models.CharField(blank=True, help_text='External verification session ID', max_length=255)),
                ('provider', models.CharField(default='onfido', help_text='Biometric verification provider', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of biometric verification', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum allowed attempts')),
                ('metadata', models.JSONField(default=dict, help_text='Additional verification metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_profile', models.OneToOneField(help_text='KYC profile associated with this biometric verification', on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='kyc.kycprofile')),
            ],
            options={
                'verbose_name': 'Biometric Verification',
                'verbose_name_plural': 'Biometric Verifications',
                'db_table': 'kyc_biometric_verification',
            },
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['status'], name='kyc_profile_status_6a8c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['verification_level'], name='kyc_profile_verific_c0cc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['risk_score'], name='kyc_profile_risk_sc_e9e4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['created_at'], name='kyc_profile_created_2788a9_idx'),
        ),
        migrations.AddIndex(
            model_name='kycnote',
            index=models.Index(fields=['kyc_profile', 'created_at'], name='kyc_note_kyc_pro_df81ae_idx'),
        ),
        migrations.AddIndex(
            model_name='kycnote',
            index=models.Index(fields=['note_type'], name='kyc_note_note_ty_42c2df_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['kyc_profile', 'document_type'], name='kyc_documen_kyc_pro_aeb99b_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['status'], name='kyc_documen_status_3b4e81_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['created_at'], name='kyc_documen_created_bd9cd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('kyc_profile', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='kycauditlog',
            index=models.Index(fields=['kyc_profile', 'created_at'], name='kyc_audit_l_kyc_pro_d517e3_idx'),
        ),
        migrations.AddIndex(
            model_name='kycauditlog',
            index=models.Index(fields=['action'], name='kyc_audit_l_action_623e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['user', 'check_type'], name='kyc_complia_user_id_e6166d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['result'], name='kyc_complia_result_e903e6_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['created_at'], name='kyc_complia_created_b9f8d9_idx'),
        ),
    ]
