# Generated by Django 5.2.8 on 2026-01-29 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0006_add_mint_tracking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_entity_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('fund', 'Investment Fund'), ('professional_individual', 'Professional Individual')], max_length=50)),
                ('registration_number', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_position', models.CharField(max_length=100)),
                ('official_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('liquidity_available', models.DecimalField(decimal_places=2, help_text='Current liquidity available', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preferred_currencies', models.JSONField(default=list)),
                ('target_ready_properties', models.BooleanField(default=True)),
                ('target_under_construction', models.BooleanField(default=False)),
                ('target_property_portfolios', models.BooleanField(default=False)),
                ('discount_rate', models.DecimalField(decimal_places=2, help_text='Current discount rate offered', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_per_transaction', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_per_month', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_month_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total amount processed this month', max_digits=20)),
                ('month_reset_date', models.DateField(blank=True, help_text='Date when monthly counter was last reset', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidity_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidity Provider',
                'verbose_name_plural': 'Liquidity Providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_requested', models.PositiveIntegerField(help_text='Number of units/tokens to exit', validators=[django.core.validators.MinValueValidator(1)])),
                ('requested_price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit requested by investor', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_requested_amount', models.DecimalField(decimal_places=2, help_text='Total amount requested (units * price)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('offered_price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit offered by LP', max_digits=20, null=True)),
                ('total_offered_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount offered by LP', max_digits=20, null=True)),
                ('lp_notes', models.TextField(blank=True, help_text='Notes from LP regarding the request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('investor_accepted_offer', models.BooleanField(blank=True, help_text="Whether investor accepted LP's offer", null=True)),
                ('investor_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the request/offer expires', null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='investments.investment')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to=settings.AUTH_USER_MODEL)),
                ('liquidity_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to='liquidity_provider.liquidityprovider')),
            ],
            options={
                'verbose_name': 'Exit Request',
                'verbose_name_plural': 'Exit Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_purchased', models.PositiveIntegerField(help_text='Number of units/tokens purchased')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Final price per unit', max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=20)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Platform fee charged', max_digits=20)),
                ('net_amount_to_investor', models.DecimalField(decimal_places=2, help_text='Net amount paid to investor', max_digits=20)),
                ('reference_number', models.CharField(help_text='Transaction reference number', max_length=50, unique=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exit_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='liquidity_provider.exitrequest')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lp_exit_transactions', to=settings.AUTH_USER_MODEL)),
                ('liquidity_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='liquidity_provider.liquidityprovider')),
            ],
            options={
                'verbose_name': 'Liquidity Transaction',
                'verbose_name_plural': 'Liquidity Transactions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='LPApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_entity_name', models.CharField(help_text='Legal name of the entity', max_length=255)),
                ('country', models.CharField(help_text='Country of registration', max_length=100)),
                ('jurisdiction', models.CharField(help_text='Legal jurisdiction', max_length=100)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('fund', 'Investment Fund'), ('professional_individual', 'Professional Individual')], help_text='Type of entity', max_length=50)),
                ('registration_number', models.CharField(help_text='Business registration number', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Company website', null=True)),
                ('contact_person_name', models.CharField(help_text='Primary contact person', max_length=255)),
                ('contact_position', models.CharField(help_text='Position/title of contact person', max_length=100)),
                ('official_email', models.EmailField(help_text='Official contact email', max_length=254)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=30)),
                ('approximate_liquidity_available', models.DecimalField(decimal_places=2, help_text='Approximate liquidity available in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preferred_currencies', models.JSONField(default=list, help_text='Preferred currencies for transactions')),
                ('average_transaction_size', models.DecimalField(decimal_places=2, help_text='Average expected transaction size in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_ready_properties', models.BooleanField(default=True, help_text='Interested in ready/completed properties')),
                ('target_under_construction', models.BooleanField(default=False, help_text='Interested in properties under construction')),
                ('target_property_portfolios', models.BooleanField(default=False, help_text='Interested in property portfolios')),
                ('expected_discount_rate', models.DecimalField(decimal_places=2, help_text='Expected discount rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_per_transaction', models.DecimalField(decimal_places=2, help_text='Maximum amount per transaction in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_per_month', models.DecimalField(decimal_places=2, help_text='Maximum total amount per month in USD', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ack_independent_provider', models.BooleanField(default=False, help_text='Acknowledges operating as independent provider')),
                ('ack_no_exit_guarantee', models.BooleanField(default=False, help_text='Acknowledges no obligation to guarantee exits')),
                ('ack_compliance_agreement', models.BooleanField(default=False, help_text='Agrees to comply with platform terms')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Internal review notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lp_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LP Application',
                'verbose_name_plural': 'LP Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='liquidityprovider',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liquidity_provider', to='liquidity_provider.lpapplication'),
        ),
    ]
