# Generated by Django 4.2.7 on 2025-09-12 23:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0002_initial'),
        ('properties', '0006_remove_installmentpayment_properties__propert_2f92c8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the blockchain network', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Network name (e.g., Ethereum Mainnet)', max_length=100)),
                ('network_type', models.CharField(choices=[('ethereum', 'Ethereum'), ('polygon', 'Polygon'), ('bsc', 'BNB Smart Chain'), ('avalanche', 'Avalanche'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism')], help_text='Type of blockchain network', max_length=20)),
                ('environment', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet'), ('devnet', 'Development')], default='testnet', help_text='Network environment', max_length=20)),
                ('chain_id', models.PositiveIntegerField(help_text='Blockchain network chain ID', unique=True)),
                ('rpc_url', models.URLField(help_text='RPC endpoint URL for blockchain interaction')),
                ('explorer_url', models.URLField(blank=True, help_text='Block explorer URL for transaction viewing', null=True)),
                ('native_currency', models.CharField(default='ETH', help_text='Native currency symbol (e.g., ETH, MATIC, BNB)', max_length=10)),
                ('gas_price_gwei', models.DecimalField(blank=True, decimal_places=2, help_text='Default gas price in Gwei', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('block_confirmation_count', models.PositiveIntegerField(default=12, help_text='Required block confirmations for transaction finality', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this network is active for deployments')),
                ('supports_eip1559', models.BooleanField(default=True, help_text='Whether network supports EIP-1559 gas pricing')),
                ('average_block_time', models.PositiveIntegerField(default=15, help_text='Average block time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blockchain Network',
                'verbose_name_plural': 'Blockchain Networks',
                'db_table': 'blockchain_network',
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the smart contract', primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('real_estate_token', 'Real Estate Token'), ('rental_distributor', 'Rental Income Distributor'), ('property_factory', 'Property Contract Factory'), ('governance', 'Governance Contract'), ('staking', 'Staking Contract'), ('marketplace', 'NFT Marketplace')], help_text='Type of smart contract', max_length=30)),
                ('contract_address', models.CharField(db_index=True, help_text='Blockchain address of the deployed contract', max_length=42)),
                ('contract_name', models.CharField(help_text='Human-readable name of the contract', max_length=100)),
                ('abi', models.JSONField(help_text='Contract ABI (Application Binary Interface)')),
                ('bytecode', models.TextField(blank=True, help_text='Contract bytecode for verification', null=True)),
                ('source_code', models.TextField(blank=True, help_text='Contract source code', null=True)),
                ('compiler_version', models.CharField(blank=True, help_text='Solidity compiler version used', max_length=20, null=True)),
                ('constructor_args', models.JSONField(default=dict, help_text='Constructor arguments used during deployment')),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('verified', 'Verified'), ('active', 'Active'), ('paused', 'Paused'), ('deprecated', 'Deprecated'), ('upgraded', 'Upgraded')], default='deployed', help_text='Current status of the contract', max_length=20)),
                ('deployment_transaction', models.CharField(blank=True, help_text='Transaction hash of contract deployment', max_length=66, null=True)),
                ('deployer_address', models.CharField(default='0x0000000000000000000000000000000000000000', help_text='Address that deployed this contract', max_length=42)),
                ('deployment_block', models.PositiveIntegerField(blank=True, help_text='Block number where contract was deployed', null=True)),
                ('deployment_gas_used', models.PositiveIntegerField(blank=True, help_text='Gas used for contract deployment', null=True)),
                ('deployment_cost', models.DecimalField(blank=True, decimal_places=8, help_text='Deployment cost in native currency', max_digits=20, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether contract is verified on block explorer')),
                ('verification_date', models.DateTimeField(blank=True, help_text='Date when contract was verified', null=True)),
                ('proxy_implementation', models.CharField(blank=True, help_text='Implementation contract address (for proxy contracts)', max_length=42, null=True)),
                ('is_proxy', models.BooleanField(default=False, help_text='Whether this is a proxy contract')),
                ('admin_addresses', models.JSONField(default=list, help_text='List of admin addresses for the contract')),
                ('metadata', models.JSONField(default=dict, help_text='Additional contract metadata and configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(help_text='Blockchain network where contract is deployed', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='blockchain.blockchainnetwork')),
                ('property_reference', models.ForeignKey(blank=True, help_text='Associated property (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_contracts', to='properties.property')),
            ],
            options={
                'verbose_name': 'Smart Contract',
                'verbose_name_plural': 'Smart Contracts',
                'db_table': 'blockchain_smart_contract',
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the transaction record', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('mint', 'Token Mint'), ('burn', 'Token Burn'), ('transfer', 'Token Transfer'), ('rental_distribution', 'Rental Distribution'), ('installment_payment', 'Installment Payment'), ('early_exit', 'Early Exit'), ('governance', 'Governance'), ('staking', 'Staking'), ('other', 'Other')], help_text='Type of blockchain transaction', max_length=30)),
                ('transaction_hash', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('from_address', models.CharField(help_text='Transaction sender address', max_length=42)),
                ('to_address', models.CharField(help_text='Transaction recipient address', max_length=42)),
                ('token_id', models.PositiveIntegerField(blank=True, help_text='Token ID (for ERC-1155 tokens)', null=True)),
                ('token_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Number of tokens involved in transaction', max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('value_wei', models.DecimalField(blank=True, decimal_places=0, help_text='Transaction value in wei', max_digits=30, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gas_limit', models.PositiveIntegerField(blank=True, help_text='Gas limit for the transaction', null=True)),
                ('gas_used', models.PositiveIntegerField(blank=True, help_text='Actual gas used by the transaction', null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=0, help_text='Gas price in wei', max_digits=15, null=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=8, help_text='Total transaction fee in native currency', max_digits=20, null=True)),
                ('block_number', models.PositiveIntegerField(blank=True, help_text='Block number where transaction was included', null=True)),
                ('block_hash', models.CharField(blank=True, help_text='Hash of block containing this transaction', max_length=66, null=True)),
                ('transaction_index', models.PositiveIntegerField(blank=True, help_text='Transaction index within the block', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('replaced', 'Replaced')], default='pending', help_text='Current status of the transaction', max_length=20)),
                ('confirmation_count', models.PositiveIntegerField(default=0, help_text='Number of block confirmations')),
                ('nonce', models.PositiveIntegerField(blank=True, help_text='Transaction nonce', null=True)),
                ('input_data', models.TextField(blank=True, help_text='Transaction input data', null=True)),
                ('function_signature', models.CharField(blank=True, help_text='Function signature (first 4 bytes of input data)', max_length=10, null=True)),
                ('decoded_input', models.JSONField(blank=True, help_text='Decoded transaction input data', null=True)),
                ('logs', models.JSONField(default=list, help_text='Transaction event logs')),
                ('receipt', models.JSONField(blank=True, help_text='Full transaction receipt', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times transaction was retried')),
                ('replaced_by', models.CharField(blank=True, help_text='Transaction hash that replaced this one', max_length=66, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional transaction metadata')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When transaction was submitted to blockchain')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When transaction was confirmed on blockchain', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Smart contract involved in this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.smartcontract')),
                ('investment_reference', models.ForeignKey(blank=True, help_text='Associated investment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='investments.investment')),
                ('property_reference', models.ForeignKey(blank=True, help_text='Associated property (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='properties.property')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
                'db_table': 'blockchain_token_transaction',
            },
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the balance record', primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text='Wallet address holding the tokens', max_length=42)),
                ('token_id', models.PositiveIntegerField(help_text='Token ID (for ERC-1155 tokens)')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Current token balance', max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Locked token balance (during lockup period)', max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Available token balance (transferable)', max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lockup_end_time', models.DateTimeField(blank=True, help_text='When token lockup period ends', null=True)),
                ('total_earned_rental', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Total rental income earned from these tokens', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_distribution_claim', models.DateTimeField(blank=True, help_text='Last time rental distribution was claimed', null=True)),
                ('is_installment_investor', models.BooleanField(default=False, help_text='Whether this is an installment investment')),
                ('installments_completed', models.PositiveIntegerField(default=0, help_text='Number of installments completed')),
                ('total_installments', models.PositiveIntegerField(default=0, help_text='Total number of installments')),
                ('last_updated_block', models.PositiveIntegerField(blank=True, help_text='Last block number when balance was updated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Token contract', on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='blockchain.smartcontract')),
                ('property_reference', models.ForeignKey(help_text='Property associated with tokens', on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to='properties.property')),
                ('user', models.ForeignKey(help_text='Token holder', on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Balance',
                'verbose_name_plural': 'Token Balances',
                'db_table': 'blockchain_token_balance',
            },
        ),
        migrations.CreateModel(
            name='RentalDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the distribution', primary_key=True, serialize=False)),
                ('distribution_id', models.PositiveIntegerField(help_text='Distribution ID on the smart contract')),
                ('total_amount', models.DecimalField(decimal_places=8, help_text='Total distribution amount', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('net_amount', models.DecimalField(decimal_places=8, help_text='Net amount after platform fees', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('platform_fee', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Platform fee deducted', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('eligible_tokens', models.PositiveIntegerField(help_text='Number of tokens eligible for distribution')),
                ('payment_token', models.CharField(default='ETH', help_text='Token used for payment (ETH, USDC, etc.)', max_length=10)),
                ('payment_token_address', models.CharField(blank=True, help_text='Address of payment token contract (null for ETH)', max_length=42, null=True)),
                ('distribution_period', models.CharField(help_text="Distribution period (e.g., '2024-01')", max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the distribution', max_length=20)),
                ('total_claimed', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Total amount claimed by investors', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('claims_processed', models.PositiveIntegerField(default=0, help_text='Number of claims processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_at', models.DateTimeField(blank=True, help_text='When distribution was processed on blockchain', null=True)),
                ('contract', models.ForeignKey(help_text='Rental distributor contract', on_delete=django.db.models.deletion.CASCADE, related_name='rental_distributions', to='blockchain.smartcontract')),
                ('distribution_transaction', models.ForeignKey(blank=True, help_text='Blockchain transaction for this distribution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_distributions', to='blockchain.tokentransaction')),
                ('property_reference', models.ForeignKey(help_text='Property for which income is distributed', on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_distributions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rental Distribution',
                'verbose_name_plural': 'Rental Distributions',
                'db_table': 'blockchain_rental_distribution',
            },
        ),
        migrations.CreateModel(
            name='GasTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slow_gas_price', models.DecimalField(decimal_places=0, help_text='Slow gas price in wei', max_digits=15)),
                ('standard_gas_price', models.DecimalField(decimal_places=0, help_text='Standard gas price in wei', max_digits=15)),
                ('fast_gas_price', models.DecimalField(decimal_places=0, help_text='Fast gas price in wei', max_digits=15)),
                ('base_fee', models.DecimalField(blank=True, decimal_places=0, help_text='Base fee (for EIP-1559 networks)', max_digits=15, null=True)),
                ('priority_fee', models.DecimalField(blank=True, decimal_places=0, help_text='Priority fee (for EIP-1559 networks)', max_digits=15, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(help_text='Blockchain network', on_delete=django.db.models.deletion.CASCADE, related_name='gas_prices', to='blockchain.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Gas Tracker',
                'verbose_name_plural': 'Gas Trackers',
                'db_table': 'blockchain_gas_tracker',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the event', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PropertyCreated', 'Property Created'), ('TokensMinted', 'Tokens Minted'), ('TokensBurned', 'Tokens Burned'), ('Transfer', 'Token Transfer'), ('RentalIncomeDistributed', 'Rental Income Distributed'), ('RentalIncomeClaimed', 'Rental Income Claimed'), ('EarlyExit', 'Early Exit'), ('InstallmentPaid', 'Installment Paid'), ('TokensGraduated', 'Tokens Graduated'), ('PropertyActivated', 'Property Activated'), ('Other', 'Other Event')], help_text='Type of event emitted', max_length=50)),
                ('event_signature', models.CharField(help_text='Event signature hash', max_length=66)),
                ('log_index', models.PositiveIntegerField(help_text='Index of this log in the transaction')),
                ('decoded_data', models.JSONField(default=dict, help_text='Decoded event data')),
                ('raw_data', models.JSONField(default=dict, help_text='Raw event log data')),
                ('topics', models.JSONField(default=list, help_text='Event topics array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(help_text='Contract that emitted this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blockchain.smartcontract')),
                ('transaction', models.ForeignKey(help_text='Transaction that emitted this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blockchain.tokentransaction')),
            ],
            options={
                'verbose_name': 'Contract Event',
                'verbose_name_plural': 'Contract Events',
                'db_table': 'blockchain_contract_event',
            },
        ),
        migrations.AddIndex(
            model_name='blockchainnetwork',
            index=models.Index(fields=['network_type', 'environment'], name='blockchain__network_b3e81f_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainnetwork',
            index=models.Index(fields=['chain_id'], name='blockchain__chain_i_d1c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainnetwork',
            index=models.Index(fields=['is_active'], name='blockchain__is_acti_b48bc4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockchainnetwork',
            unique_together={('network_type', 'environment')},
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['contract', 'transaction_type'], name='blockchain__contrac_7ad5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_872436_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['status', 'submitted_at'], name='blockchain__status_f05603_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='blockchain__user_id_35ee2a_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['property_reference', 'transaction_type'], name='blockchain__propert_6bc749_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['block_number'], name='blockchain__block_n_e12921_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['confirmation_count'], name='blockchain__confirm_a9204c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenbalance',
            index=models.Index(fields=['user', 'contract'], name='blockchain__user_id_caa6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenbalance',
            index=models.Index(fields=['wallet_address', 'token_id'], name='blockchain__wallet__da023f_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenbalance',
            index=models.Index(fields=['property_reference', 'user'], name='blockchain__propert_ed7dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenbalance',
            index=models.Index(fields=['lockup_end_time'], name='blockchain__lockup__69a012_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenbalance',
            unique_together={('contract', 'user', 'property_reference', 'token_id')},
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['network', 'contract_type'], name='blockchain__network_b66505_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['contract_address'], name='blockchain__contrac_01e2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['status', 'created_at'], name='blockchain__status_9026b4_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['property_reference'], name='blockchain__propert_b1844d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='smartcontract',
            unique_together={('network', 'contract_address')},
        ),
        migrations.AddIndex(
            model_name='rentaldistribution',
            index=models.Index(fields=['property_reference', 'distribution_period'], name='blockchain__propert_7daca8_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaldistribution',
            index=models.Index(fields=['contract', 'distribution_id'], name='blockchain__contrac_fbd75f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaldistribution',
            index=models.Index(fields=['status', 'created_at'], name='blockchain__status_ac9eff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentaldistribution',
            unique_together={('contract', 'property_reference', 'distribution_id')},
        ),
        migrations.AddIndex(
            model_name='gastracker',
            index=models.Index(fields=['network', 'timestamp'], name='blockchain__network_b95626_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['transaction', 'log_index'], name='blockchain__transac_84e849_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['contract', 'event_type'], name='blockchain__contrac_e34e40_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['event_signature'], name='blockchain__event_s_af1c49_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['created_at'], name='blockchain__created_32b6eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractevent',
            unique_together={('transaction', 'log_index')},
        ),
    ]
