# Generated by Django 5.2.8 on 2026-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainnetwork',
            name='backup_rpc_urls',
            field=models.JSONField(blank=True, default=list, help_text="List of backup RPC endpoint URLs for failover (e.g., ['https://backup1.com', 'https://backup2.com'])"),
        ),
        migrations.AlterField(
            model_name='blockchainnetwork',
            name='rpc_url',
            field=models.URLField(help_text='Primary RPC endpoint URL for blockchain interaction'),
        ),
    ]
