# Generated by Django 6.0.5 on 2026-05-17 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0007_investment_accredited_at_investment_time_and_more'),
        ('marketplace', '0003_initial'),
        ('properties', '0011_add_spv_fields_to_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Legal name of the SPV (e.g., "Capimax Property 042, LLC")', max_length=255)),
                ('entity_type', models.CharField(choices=[('llc', 'Limited Liability Company'), ('lp', 'Limited Partnership'), ('corp', 'Corporation'), ('trust', 'Trust'), ('other', 'Other')], default='llc', max_length=20)),
                ('jurisdiction', models.CharField(help_text='Formation jurisdiction (e.g., "Delaware, USA", "BVI", "DIFC")', max_length=100)),
                ('registration_number', models.CharField(help_text='Registration/file number assigned by the formation authority', max_length=100)),
                ('formation_date', models.DateField()),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=255)),
                ('registered_agent_name', models.CharField(blank=True, max_length=255)),
                ('registered_agent_address', models.TextField(blank=True)),
                ('allowed_investor_jurisdictions', models.JSONField(blank=True, default=list, help_text='ISO country codes whose residents may invest. Empty = all.')),
                ('requires_accredited_investors', models.BooleanField(default=False, help_text='If True, only KYC-accredited investors may hold tokens.')),
                ('status', models.CharField(choices=[('pre_formation', 'Pre-Formation'), ('active', 'Active'), ('suspended', 'Suspended'), ('dissolved', 'Dissolved')], default='pre_formation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering_memorandum_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offering_memorandum_for_entities', to='properties.propertydocument')),
                ('operating_agreement_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_agreement_for_entities', to='properties.propertydocument')),
            ],
            options={
                'verbose_name': 'Legal Entity (SPV)',
                'verbose_name_plural': 'Legal Entities (SPVs)',
                'db_table': 'legal_entities',
            },
        ),
        migrations.CreateModel(
            name='DistributionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares_at_snapshot', models.PositiveBigIntegerField()),
                ('allocated_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='properties.rentalincomedistribution')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_allocations', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_allocations', to='legal.legalentity')),
            ],
            options={
                'db_table': 'legal_distribution_allocations',
            },
        ),
        migrations.CreateModel(
            name='CapTableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens_delta', models.BigIntegerField()),
                ('tokens_balance_after', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(choices=[('mint', 'Primary Issuance (Mint)'), ('secondary_buy', 'Secondary Market Purchase'), ('secondary_sell', 'Secondary Market Sale'), ('burn', 'Token Burn'), ('early_exit', 'Early Exit / Buyback'), ('adjustment', 'Manual Adjustment (Admin)')], max_length=24)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cap_table_entries', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_cap_table_entries', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cap_table_entries', to='investments.investment')),
                ('trade_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cap_table_entries', to='marketplace.tradetransaction')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cap_table_entries', to='legal.legalentity')),
            ],
            options={
                'db_table': 'legal_cap_table_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_amount', models.PositiveIntegerField()),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('token_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('lockup_months', models.PositiveIntegerField(default=12)),
                ('expected_return_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fee_schedule', models.JSONField(blank=True, default=dict, help_text='Snapshot of the fee structure at signing.')),
                ('pdf_document', models.FileField(blank=True, help_text='Generated PDF of the signed agreement', null=True, upload_to='subscription_agreements/%Y/%m/')),
                ('signature_hash', models.CharField(blank=True, help_text='SHA-256 hash of the PDF at signing time', max_length=64)),
                ('investor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('investor_signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('investor_signed_user_agent', models.CharField(blank=True, max_length=512)),
                ('investor_typed_name', models.CharField(blank=True, max_length=255)),
                ('company_signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_signature', 'Pending Investor Signature'), ('signed', 'Signed by Investor'), ('countersigned', 'Countersigned by Company'), ('voided', 'Voided')], default='pending_signature', max_length=20)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countersigned_agreements', to=settings.AUTH_USER_MODEL)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_agreement', to='investments.investment')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_agreements', to='legal.legalentity')),
            ],
            options={
                'db_table': 'legal_subscription_agreements',
            },
        ),
        migrations.AddIndex(
            model_name='legalentity',
            index=models.Index(fields=['status'], name='legal_entit_status_e7c646_idx'),
        ),
        migrations.AddIndex(
            model_name='legalentity',
            index=models.Index(fields=['jurisdiction'], name='legal_entit_jurisdi_fb1457_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('jurisdiction', 'registration_number'), name='uniq_legal_entity_jurisdiction_regnum'),
        ),
        migrations.AddIndex(
            model_name='distributionallocation',
            index=models.Index(fields=['holder', 'paid_at'], name='legal_distr_holder__f5e746_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionallocation',
            index=models.Index(fields=['distribution', 'paid_at'], name='legal_distr_distrib_4d2470_idx'),
        ),
        migrations.AddConstraint(
            model_name='distributionallocation',
            constraint=models.UniqueConstraint(fields=('distribution', 'holder'), name='uniq_allocation_distribution_holder'),
        ),
        migrations.AddIndex(
            model_name='captableentry',
            index=models.Index(fields=['legal_entity', 'holder', 'timestamp'], name='legal_cap_t_legal_e_2cca91_idx'),
        ),
        migrations.AddIndex(
            model_name='captableentry',
            index=models.Index(fields=['blockchain_tx_hash'], name='legal_cap_t_blockch_3bf971_idx'),
        ),
        migrations.AddIndex(
            model_name='captableentry',
            index=models.Index(fields=['event_type', 'timestamp'], name='legal_cap_t_event_t_78ea2d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionagreement',
            index=models.Index(fields=['legal_entity', 'status'], name='legal_subsc_legal_e_8039b7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionagreement',
            index=models.Index(fields=['investor_signed_at'], name='legal_subsc_investo_896c16_idx'),
        ),
    ]
