# Generated by Django 4.2.7 on 2025-08-29 15:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the auto investment', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to invest each period', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], help_text='Investment frequency', max_length=20)),
                ('payment_method', models.JSONField(help_text='Payment method for auto investments')),
                ('start_date', models.DateTimeField(help_text='Start date for auto investments')),
                ('end_date', models.DateTimeField(blank=True, help_text='End date for auto investments (optional)', null=True)),
                ('max_total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total amount to invest (optional)', max_digits=12, null=True)),
                ('next_execution', models.DateTimeField(help_text='Next scheduled investment date')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invested so far', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', help_text='Status of auto investment plan', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auto Investment',
                'verbose_name_plural': 'Auto Investments',
                'db_table': 'investments_auto_investment',
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the dividend payment', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Dividend amount in specified currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Currency of dividend payment', max_length=10)),
                ('payment_date', models.DateTimeField(help_text='Date when dividend was/will be paid')),
                ('period_start', models.DateTimeField(help_text='Start of dividend period')),
                ('period_end', models.DateTimeField(help_text='End of dividend period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of dividend payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dividend Payment',
                'verbose_name_plural': 'Dividend Payments',
                'db_table': 'investments_dividend_payment',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the installment payment', primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField(help_text='Installment sequence number (1, 2, 3...)')),
                ('due_date', models.DateTimeField(help_text='Due date for this installment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Installment amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of this installment', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when installment was paid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Installment Payment',
                'verbose_name_plural': 'Installment Payments',
                'db_table': 'investments_installment_payment',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the investment', primary_key=True, serialize=False)),
                ('token_amount', models.PositiveIntegerField(help_text='Number of tokens being purchased', validators=[django.core.validators.MinValueValidator(1)])),
                ('investment_amount', models.DecimalField(decimal_places=2, help_text='Total investment amount in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the investment', max_length=20)),
                ('payment_method', models.JSONField(default=dict, help_text='Payment method details and metadata')),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True)),
                ('blockchain_confirmed', models.BooleanField(default=False, help_text='Whether blockchain transaction is confirmed')),
                ('confirmation_blocks', models.PositiveIntegerField(default=0, help_text='Number of blockchain confirmation blocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when investment was completed', null=True)),
                ('property_investment', models.ForeignKey(help_text='Property being invested in', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='properties.property')),
                ('user', models.ForeignKey(help_text='User making the investment', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments_investment',
            },
        ),
        migrations.CreateModel(
            name='TokenReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_amount', models.PositiveIntegerField(help_text='Number of tokens reserved', validators=[django.core.validators.MinValueValidator(1)])),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the reservation expires')),
                ('released', models.BooleanField(default=False, help_text='Whether tokens have been released')),
                ('property_investment', models.ForeignKey(help_text='Property with reserved tokens', on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(help_text='User reserving tokens', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Reservation',
                'verbose_name_plural': 'Token Reservations',
                'db_table': 'investments_token_reservation',
            },
        ),
        migrations.CreateModel(
            name='InvestmentWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the withdrawal', primary_key=True, serialize=False)),
                ('token_amount', models.PositiveIntegerField(help_text='Number of tokens to withdraw', validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_amount', models.DecimalField(decimal_places=2, help_text='Estimated withdrawal amount in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Processing fee for withdrawal', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of withdrawal request', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_completion', models.DateTimeField(help_text='Estimated completion date')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Actual completion timestamp', null=True)),
                ('investment', models.ForeignKey(help_text='Original investment being withdrawn', on_delete=django.db.models.deletion.CASCADE, to='investments.investment')),
            ],
            options={
                'verbose_name': 'Investment Withdrawal',
                'verbose_name_plural': 'Investment Withdrawals',
                'db_table': 'investments_investment_withdrawal',
            },
        ),
    ]
