# Generated by Django 4.2.7 on 2024-09-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='transaction_hash',
            new_name='blockchain_tx_hash',
        ),
        migrations.AddField(
            model_name='investment',
            name='tokens_minted',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens actually minted on blockchain'),
        ),
        migrations.AddField(
            model_name='investment',
            name='token_mint_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash for token minting', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='lockup_end_date',
            field=models.DateTimeField(blank=True, help_text='When token lockup period ends', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='is_installment_investment',
            field=models.BooleanField(default=False, help_text='Whether this is an installment-based investment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='installments_completed',
            field=models.PositiveIntegerField(default=0, help_text='Number of installments completed'),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_installments',
            field=models.PositiveIntegerField(default=1, help_text='Total number of installments planned'),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_rental_earned',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Total rental income earned from this investment', max_digits=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_rental_claim',
            field=models.DateTimeField(blank=True, help_text='Last time rental income was claimed', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='blockchain_metadata',
            field=models.JSONField(default=dict, help_text='Additional blockchain-specific metadata'),
        ),
        # Add new status choices to existing field
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'), 
                    ('processing', 'Processing'), 
                    ('confirmed', 'Confirmed'),  # New status
                    ('active', 'Active'),  # New status for minted tokens
                    ('completed', 'Completed'), 
                    ('failed', 'Failed'), 
                    ('cancelled', 'Cancelled')
                ],
                default='pending',
                help_text='Current status of the investment',
                max_length=20
            ),
        ),
        # Update InstallmentPayment with blockchain integration
        migrations.AddField(
            model_name='installmentpayment',
            name='tokens_released',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens released for this installment'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='token_release_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash for token release', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='blockchain_confirmed',
            field=models.BooleanField(default=False, help_text='Whether blockchain transaction is confirmed'),
        ),
    ]