# Generated by Django 4.2.7 on 2025-08-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Associated payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='property_investment',
            field=models.ForeignKey(help_text='Property being invested in', on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='user',
            field=models.ForeignKey(help_text='User making the installment payment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='investment',
            field=models.ForeignKey(help_text='Investment receiving dividend', on_delete=django.db.models.deletion.CASCADE, to='investments.investment'),
        ),
        migrations.AddField(
            model_name='autoinvestment',
            name='property_investment',
            field=models.ForeignKey(help_text='Property to auto invest in', on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='autoinvestment',
            name='user',
            field=models.ForeignKey(help_text='User setting up auto investment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tokenreservation',
            index=models.Index(fields=['user', 'property_investment'], name='investments_user_id_cfbf8d_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenreservation',
            index=models.Index(fields=['expires_at', 'released'], name='investments_expires_4a84d0_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenreservation',
            index=models.Index(fields=['property_investment', 'released'], name='investments_propert_a1d0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentwithdrawal',
            index=models.Index(fields=['investment', 'status'], name='investments_investm_563626_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentwithdrawal',
            index=models.Index(fields=['status', 'requested_at'], name='investments_status_2cf5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentwithdrawal',
            index=models.Index(fields=['estimated_completion'], name='investments_estimat_73a232_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['property_investment', 'status'], name='investments_propert_8703c0_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['created_at'], name='investments_created_962852_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'created_at'], name='investments_status_93af78_idx'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('token_amount__gt', 0)), name='investment_token_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.CheckConstraint(condition=models.Q(('investment_amount__gt', 0)), name='investment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_e5456b_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['due_date', 'status'], name='investments_due_dat_4097fb_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentpayment',
            index=models.Index(fields=['property_investment', 'status'], name='investments_propert_bf65fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installmentpayment',
            unique_together={('user', 'property_investment', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['investment', 'payment_date'], name='investments_investm_5b0728_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['status', 'payment_date'], name='investments_status_a8442e_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['period_start', 'period_end'], name='investments_period__74443b_idx'),
        ),
        migrations.AddIndex(
            model_name='autoinvestment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_a45f97_idx'),
        ),
        migrations.AddIndex(
            model_name='autoinvestment',
            index=models.Index(fields=['next_execution', 'status'], name='investments_next_ex_bb267f_idx'),
        ),
        migrations.AddIndex(
            model_name='autoinvestment',
            index=models.Index(fields=['property_investment', 'status'], name='investments_propert_a866cc_idx'),
        ),
    ]
