# Generated by Django 4.2.7 on 2025-09-12 23:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0006_remove_installmentpayment_properties__propert_2f92c8_idx_and_more'),
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the cart', primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checkout', 'In Checkout'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', help_text='Current status of the cart', max_length=20)),
                ('total_properties', models.PositiveIntegerField(default=0, help_text='Total number of properties in cart')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total number of tokens selected')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total investment amount for all cart items', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_annual_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated annual return for cart investments', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='User notes about the cart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When cart expires (for anonymous users)', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this cart', on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Cart',
                'verbose_name_plural': 'Investment Carts',
                'db_table': 'investments_cart',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Specific notes for this property in this comparison')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated comparison score', max_digits=5, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comparison Property',
                'verbose_name_plural': 'Comparison Properties',
                'db_table': 'investments_comparison_property',
            },
        ),
        migrations.CreateModel(
            name='PropertyComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the comparison', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-defined name for this comparison', max_length=255)),
                ('comparison_criteria', models.JSONField(default=dict, help_text='Criteria and weights used for comparison')),
                ('notes', models.TextField(blank=True, help_text='User notes about the comparison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.ManyToManyField(help_text='Properties being compared', through='investments.ComparisonProperty', to='properties.property')),
                ('user', models.ForeignKey(help_text='User performing the comparison', on_delete=django.db.models.deletion.CASCADE, related_name='property_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Comparison',
                'verbose_name_plural': 'Property Comparisons',
                'db_table': 'investments_property_comparison',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='comparisonproperty',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_properties', to='investments.propertycomparison'),
        ),
        migrations.AddField(
            model_name='comparisonproperty',
            name='property_investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='properties.property'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the cart item', primary_key=True, serialize=False)),
                ('tokens_quantity', models.PositiveIntegerField(help_text='Number of tokens selected for purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_token', models.DecimalField(decimal_places=2, help_text='Price per token at time of addition to cart', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this cart item', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('installment_payment', models.BooleanField(default=False, help_text='Whether user wants installment payment for this item')),
                ('installment_months', models.PositiveIntegerField(blank=True, help_text='Number of installment months (if applicable)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('notes', models.TextField(blank=True, help_text='User notes for this specific investment')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='investments.cart')),
                ('property_investment', models.ForeignKey(help_text='Property selected for investment', on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'investments_cart_item',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertycomparison',
            index=models.Index(fields=['user', 'created_at'], name='investments_user_id_633f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycomparison',
            index=models.Index(fields=['created_at'], name='investments_created_783ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonproperty',
            index=models.Index(fields=['comparison', 'score'], name='investments_compari_3d8f09_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonproperty',
            index=models.Index(fields=['added_at'], name='investments_added_a_edd625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comparisonproperty',
            unique_together={('comparison', 'property_investment')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'added_at'], name='investments_cart_id_38b119_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['property_investment'], name='investments_propert_7cd810_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['price_per_token'], name='investments_price_p_fb9e56_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(('tokens_quantity__gt', 0)), name='cart_item_tokens_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gt', 0)), name='cart_item_total_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'property_investment')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_60c65f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'status'], name='investments_session_d04a83_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'created_at'], name='investments_status_05c4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='investments_expires_08bb9a_idx'),
        ),
    ]
