# Generated by Django 4.2.7 on 2025-09-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_add_blockchain_fields'),
        ('investments', '0003_cart_comparisonproperty_propertycomparison_and_more'),
    ]

    operations = [
    ]
