# Generated by Django 4.2.7 on 2025-09-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_merge_20250913_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpayment',
            name='blockchain_confirmed',
        ),
        migrations.RemoveField(
            model_name='installmentpayment',
            name='token_release_tx_hash',
        ),
        migrations.RemoveField(
            model_name='installmentpayment',
            name='tokens_released',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='blockchain_metadata',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='blockchain_tx_hash',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='installments_completed',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='is_installment_investment',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='last_rental_claim',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='lockup_end_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='token_mint_tx_hash',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='tokens_minted',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='total_installments',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='total_rental_earned',
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the investment', max_length=20),
        ),
    ]
