# Generated by Django 5.2.8 on 2026-01-08 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_remove_installmentpayment_blockchain_confirmed_and_more'),
        ('properties', '0008_remove_property_blockchain_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique key to prevent double processing', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='mint_error',
            field=models.TextField(blank=True, help_text='Last mint error message', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='mint_last_attempt',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last mint attempt', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='mint_retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of mint retry attempts'),
        ),
        migrations.AddField(
            model_name='investment',
            name='mint_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When next mint attempt is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='tokens_minted',
            field=models.PositiveIntegerField(default=0, help_text='Actual number of tokens minted on-chain'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('payment_confirmed', 'Payment Confirmed'), ('pending_mint', 'Pending Mint'), ('minting', 'Minting'), ('completed', 'Completed'), ('mint_failed', 'Mint Failed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the investment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'mint_scheduled_at'], name='investments_status_ab04e6_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['idempotency_key'], name='investments_idempot_82e8e8_idx'),
        ),
    ]
