# Generated by Django 6.0.5 on 2026-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_add_mint_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='accredited_at_investment_time',
            field=models.BooleanField(default=False, help_text="Snapshot of the investor's accredited status at investment creation. Used for audit trail even if status changes later."),
        ),
        migrations.AddField(
            model_name='investment',
            name='jurisdiction_at_investment_time',
            field=models.CharField(blank=True, help_text='ISO country code of investor at investment creation.', max_length=2),
        ),
        migrations.AddField(
            model_name='investment',
            name='lockup_end_date',
            field=models.DateTimeField(blank=True, help_text="Date/time when this investment's tokens become transferable on the secondary market. Set when the mint completes; enforced by the marketplace listing validator and the on-chain compliance registry.", null=True),
        ),
    ]
