# Generated by Django 4.2.7 on 2025-08-29 15:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address - used for login", max_length=254, unique=True)),
                ('role', models.CharField(choices=[('investor', 'Investor'), ('property_owner', 'Property Owner'), ('broker', 'Broker'), ('admin', 'Admin')], default='investor', help_text="User's role in the platform", max_length=20)),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True)),
                ('country', models.CharField(help_text="User's country of residence", max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('address', models.TextField(blank=True, help_text="User's physical address", null=True)),
                ('city', models.CharField(blank=True, help_text="User's city", max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text="User's state/province", max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text="User's postal/zip code", max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has completed email verification')),
                ('wallet_address', models.CharField(blank=True, help_text="User's blockchain wallet address", max_length=255, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled')),
                ('two_factor_secret', models.CharField(blank=True, help_text='Secret key for 2FA token generation', max_length=32, null=True)),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='Backup codes for 2FA recovery')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('login_attempts', models.PositiveIntegerField(default=0, help_text='Number of failed login attempts')),
                ('is_suspended', models.BooleanField(default=False, help_text='Whether the user account is suspended')),
                ('suspension_reason', models.TextField(blank=True, help_text='Reason for account suspension', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the session')),
                ('user_agent', models.TextField(help_text='Browser user agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is active')),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'accounts_user_session',
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_f3bc3f_idx'), models.Index(fields=['session_key'], name='accounts_us_session_5ce38e_idx'), models.Index(fields=['created_at'], name='accounts_us_created_d86270_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for password reset')),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('used', models.BooleanField(default=False, help_text='Whether the token has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User requesting password reset', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'accounts_password_reset_token',
                'indexes': [models.Index(fields=['token'], name='accounts_pa_token_3e0820_idx'), models.Index(fields=['expires_at'], name='accounts_pa_expires_682fbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for email verification')),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('verified', models.BooleanField(default=False, help_text='Whether email has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User to verify email for', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'accounts_email_verification_token',
                'indexes': [models.Index(fields=['token'], name='accounts_em_token_5a6f4a_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_af5955_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='accounts_us_is_veri_fa45d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
    ]
