# Generated by Django 5.1.4 on 2025-09-17 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('property_owner', 'Property Owner'), ('admin', 'Admin')], default='investor', help_text="User's role in the platform", max_length=20),
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('investor', 'Investor'), ('property_owner', 'Property Owner'), ('admin', 'Admin')], help_text='Role assigned to the user', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the user's primary role")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this role was assigned')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin user who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User assigned to this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'accounts_user_role_assignment',
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_9d0ccf_idx'), models.Index(fields=['role', 'is_active'], name='accounts_us_role_3ce401_idx'), models.Index(fields=['user', 'is_primary'], name='accounts_us_user_id_496771_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
