# Generated by Django 5.1.4 on 2025-09-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_role_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(blank=True, help_text='6-digit verification code', max_length=6, null=True),
        ),
    ]
