# Generated by Django 5.2.8 on 2025-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationtoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('property_owner', 'Property Owner'), ('broker', 'Broker'), ('admin', 'Admin')], default='investor', help_text="User's role in the platform", max_length=20),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('property_owner', 'Property Owner'), ('broker', 'Broker'), ('admin', 'Admin')], help_text='Role assigned to the user', max_length=20),
        ),
    ]
