# Generated by Django 4.2.7 on 2025-08-30 12:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_propertyanalytics_propertyviewlog_propertymarketdata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the milestone', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Milestone title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the milestone')),
                ('category', models.CharField(choices=[('foundation', 'Foundation'), ('structure', 'Structure'), ('roofing', 'Roofing'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('landscaping', 'Landscaping'), ('final_inspection', 'Final Inspection'), ('occupancy', 'Occupancy')], help_text='Category of the milestone', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the milestone', max_length=20)),
                ('planned_start_date', models.DateField(help_text='Planned start date for the milestone')),
                ('planned_completion_date', models.DateField(help_text='Planned completion date for the milestone')),
                ('actual_start_date', models.DateField(blank=True, help_text='Actual start date of the milestone', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual completion date of the milestone', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Progress percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for this milestone', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost for this milestone', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('contractor', models.CharField(blank=True, help_text='Contractor responsible for this milestone', max_length=255)),
                ('inspection_date', models.DateTimeField(blank=True, help_text='Date and time of inspection', null=True)),
                ('inspection_notes', models.TextField(blank=True, help_text="Inspector's notes and comments")),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this milestone in the construction sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, help_text='Inspector who verified this milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_milestones', to=settings.AUTH_USER_MODEL)),
                ('property_obj', models.ForeignKey(help_text='Property this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='construction_milestones', to='properties.property')),
            ],
            options={
                'verbose_name': 'Construction Milestone',
                'verbose_name_plural': 'Construction Milestones',
                'db_table': 'construction_milestone',
                'ordering': ['order', 'planned_start_date'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Update title', max_length=255)),
                ('description', models.TextField(help_text='Update description')),
                ('progress_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Change in progress percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='User who created this update', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(help_text='Milestone this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='construction.constructionmilestone')),
            ],
            options={
                'verbose_name': 'Milestone Update',
                'verbose_name_plural': 'Milestone Updates',
                'db_table': 'construction_milestone_update',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['milestone', 'created_at'], name='constructio_milesto_500223_idx'), models.Index(fields=['author'], name='constructio_author__4f8c36_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilestoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Milestone progress image', upload_to='milestone_images/')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=255)),
                ('taken_at', models.DateTimeField(auto_now_add=True, help_text='When the image was taken')),
                ('milestone', models.ForeignKey(help_text='Milestone this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='construction.constructionmilestone')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this image', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Image',
                'verbose_name_plural': 'Milestone Images',
                'db_table': 'construction_milestone_image',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['milestone', 'taken_at'], name='constructio_milesto_69eef4_idx'), models.Index(fields=['uploaded_by'], name='constructio_uploade_4a9111_idx')],
            },
        ),
        migrations.CreateModel(
            name='MilestoneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name', max_length=255)),
                ('document', models.FileField(help_text='Document file', upload_to='milestone_documents/')),
                ('document_type', models.CharField(help_text='Type of document (e.g., permit, certificate, inspection_report)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(help_text='Milestone this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='construction.constructionmilestone')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Document',
                'verbose_name_plural': 'Milestone Documents',
                'db_table': 'construction_milestone_document',
                'indexes': [models.Index(fields=['milestone', 'document_type'], name='constructio_milesto_c73504_idx'), models.Index(fields=['uploaded_at'], name='constructio_uploade_a8a468_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['property_obj', 'status'], name='constructio_propert_b63870_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['category', 'status'], name='constructio_categor_997a17_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['planned_start_date'], name='constructio_planned_a49f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['planned_completion_date'], name='constructio_planned_3ca6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['order'], name='constructio_order_95313c_idx'),
        ),
    ]
