# Generated by Django 6.0.5 on 2026-05-17 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user.suspend', 'Suspend User'), ('user.unsuspend', 'Unsuspend User'), ('user.kyc_override', 'KYC Status Override'), ('user.role_change', 'User Role Change'), ('property.approve', 'Approve Property'), ('property.reject', 'Reject Property'), ('property.price_change', 'Property Price Change'), ('property.status_change', 'Property Status Change'), ('investment.manual_refund', 'Manual Refund'), ('investment.force_complete', 'Force Complete Investment'), ('payment.reverse', 'Reverse Payment'), ('marketplace.escrow_override', 'Escrow Admin Override'), ('marketplace.listing_force_cancel', 'Force Cancel Listing'), ('compliance.cap_table_adjustment', 'Cap Table Adjustment'), ('compliance.override', 'Compliance Hit Override'), ('other', 'Other')], help_text='Type of administrative action.', max_length=64)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, help_text='Human reason. Required for high-severity actions.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='The admin user who performed this action.', on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'admin_panel_admin_actions',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='admin_panel_actor_i_9458c5_idx'), models.Index(fields=['target_content_type', 'target_object_id', 'timestamp'], name='admin_panel_target__a059e9_idx'), models.Index(fields=['action', 'timestamp'], name='admin_panel_action_3edae7_idx')],
            },
        ),
    ]
