# Generated by Django 4.2.7 on 2025-08-29 15:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the payment', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Payment currency', max_length=10)),
                ('payment_method', models.CharField(choices=[('cryptocurrency', 'Cryptocurrency'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], help_text='Payment method used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash (for crypto payments)', max_length=255, null=True)),
                ('payment_intent_id', models.CharField(blank=True, help_text="Payment provider's payment intent ID", max_length=255, null=True)),
                ('external_transaction_id', models.CharField(blank=True, help_text='External payment provider transaction ID', max_length=255, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Processing fee charged', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after fees', max_digits=12)),
                ('metadata', models.JSONField(default=dict, help_text='Additional payment metadata and provider-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('investment', models.ForeignKey(blank=True, help_text='Investment this payment is for (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.investment')),
                ('user', models.ForeignKey(help_text='User making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_payment',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the payment method', primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('cryptocurrency', 'Cryptocurrency'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], help_text='Type of payment method', max_length=20)),
                ('display_name', models.CharField(help_text='User-friendly display name for the payment method', max_length=255)),
                ('last_four', models.CharField(blank=True, help_text='Last four digits (for cards/accounts)', max_length=4)),
                ('expiry_date', models.CharField(blank=True, help_text='Expiry date in MM/YYYY format (for cards)', max_length=7)),
                ('brand', models.CharField(blank=True, help_text='Card brand or payment method brand', max_length=50)),
                ('wallet_address', models.CharField(blank=True, help_text='Cryptocurrency wallet address', max_length=255)),
                ('network', models.CharField(blank=True, help_text='Blockchain network (for crypto)', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default payment method")),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the payment method is verified')),
                ('external_id', models.CharField(blank=True, help_text='External provider ID (Stripe customer ID, etc.)', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='Additional payment method metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment Method',
                'verbose_name_plural': 'User Payment Methods',
                'db_table': 'payments_user_payment_method',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the refund', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(help_text='Reason for the refund')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the refund', max_length=20)),
                ('external_refund_id', models.CharField(blank=True, help_text='External payment provider refund ID', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(help_text='Original payment being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'payments_refund',
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the recurring payment', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for each payment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Payment currency', max_length=10)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], help_text='Payment frequency', max_length=20)),
                ('start_date', models.DateTimeField(help_text='Start date for recurring payments')),
                ('end_date', models.DateTimeField(blank=True, help_text='End date for recurring payments (optional)', null=True)),
                ('next_payment', models.DateTimeField(help_text='Next scheduled payment date')),
                ('purpose', models.CharField(choices=[('investment', 'Investment'), ('wallet_topup', 'Wallet Top-up')], help_text='Purpose of recurring payments', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', help_text='Status of recurring payment', max_length=20)),
                ('total_payments', models.PositiveIntegerField(default=0, help_text='Total number of payments made')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(blank=True, help_text='Target investment (if purpose is investment)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.investment')),
                ('payment_method', models.ForeignKey(help_text='Payment method to use', on_delete=django.db.models.deletion.CASCADE, to='payments.userpaymentmethod')),
                ('user', models.ForeignKey(help_text='User setting up recurring payment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Payment',
                'verbose_name_plural': 'Recurring Payments',
                'db_table': 'payments_recurring_payment',
            },
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(help_text='Wallet address used for payment', max_length=255)),
                ('network', models.CharField(help_text='Blockchain network (Ethereum, Polygon, etc.)', max_length=50)),
                ('gas_limit', models.PositiveIntegerField(blank=True, help_text='Gas limit for the transaction', null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=8, help_text="Gas price in network's base unit", max_digits=20, null=True)),
                ('confirmation_blocks_required', models.PositiveIntegerField(default=12, help_text='Number of confirmations required')),
                ('confirmations', models.PositiveIntegerField(default=0, help_text='Current number of confirmations')),
                ('block_height', models.PositiveIntegerField(blank=True, help_text='Block height when transaction was mined', null=True)),
                ('payment', models.OneToOneField(help_text='Associated payment record', on_delete=django.db.models.deletion.CASCADE, related_name='crypto_details', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Crypto Payment',
                'verbose_name_plural': 'Crypto Payments',
                'db_table': 'payments_crypto_payment',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the wallet transaction', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('refund', 'Refund')], help_text='Type of wallet transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Transaction amount (positive for credits, negative for debits)', max_digits=15)),
                ('currency', models.CharField(help_text='Currency of the transaction', max_length=10)),
                ('balance_before', models.DecimalField(decimal_places=8, help_text='Balance before this transaction', max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=8, help_text='Balance after this transaction', max_digits=15)),
                ('reference_id', models.UUIDField(blank=True, help_text='Reference ID to payment, investment, etc.', null=True)),
                ('description', models.TextField(help_text='Transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User whose wallet this transaction affects', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'payments_wallet_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='payments_wa_user_id_7af277_idx'), models.Index(fields=['transaction_type', 'created_at'], name='payments_wa_transac_95fbb4_idx'), models.Index(fields=['currency', 'created_at'], name='payments_wa_currenc_62f032_idx'), models.Index(fields=['reference_id'], name='payments_wa_referen_d29c03_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Currency code (USD, BTC, ETH, etc.)', max_length=10)),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Available balance for spending', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pending_balance', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Balance pending confirmation', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Balance locked for pending transactions', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this wallet balance', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Balance',
                'verbose_name_plural': 'Wallet Balances',
                'db_table': 'payments_wallet_balance',
                'indexes': [models.Index(fields=['user', 'currency'], name='payments_wa_user_id_0a5f80_idx'), models.Index(fields=['currency'], name='payments_wa_currenc_354653_idx')],
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user', 'method_type'], name='payments_us_user_id_5e130a_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='payments_us_user_id_b7cfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['external_id'], name='payments_us_externa_5fa432_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='payments_re_payment_4444a0_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'created_at'], name='payments_re_status_698972_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['external_refund_id'], name='payments_re_externa_fb429b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['user', 'status'], name='payments_re_user_id_621281_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['next_payment', 'status'], name='payments_re_next_pa_1f33c2_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['purpose', 'status'], name='payments_re_purpose_e10561_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='payments_pa_payment_11cbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_transaction_id'], name='payments_pa_externa_77ac9f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_intent_id'], name='payments_pa_payment_7ccbf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('processing_fee__gte', 0)), name='payment_fee_non_negative'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['wallet_address'], name='payments_cr_wallet__27ba56_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['network'], name='payments_cr_network_2a891c_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['confirmations'], name='payments_cr_confirm_d939af_idx'),
        ),
    ]
