# Generated by Django 4.2.7 on 2025-09-12 23:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(help_text='Base currency code (e.g., USD)', max_length=10)),
                ('target_currency', models.CharField(help_text='Target currency code (e.g., BTC, ETH, EUR)', max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate from base to target currency', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('inverse_rate', models.DecimalField(decimal_places=8, help_text='Inverse exchange rate (target to base)', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('source', models.CharField(default='CoinGecko', help_text='Source of exchange rate data', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this rate was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currency Exchange Rates',
                'db_table': 'payments_currency_exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='QRCodePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the QR payment', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Payment amount requested', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('wallet_address', models.CharField(help_text='Deposit address for payment', max_length=42)),
                ('qr_code_data', models.TextField(help_text='QR code data string (URI format)')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', help_text='QR code status', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When QR code expires')),
                ('used_at', models.DateTimeField(blank=True, help_text='When QR code was used for payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QR Code Payment',
                'verbose_name_plural': 'QR Code Payments',
                'db_table': 'payments_qr_code_payment',
            },
        ),
        migrations.CreateModel(
            name='WalletDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the deposit', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Deposit amount', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('transaction_hash', models.CharField(help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('from_address', models.CharField(help_text='Source wallet address', max_length=42)),
                ('to_address', models.CharField(help_text='Destination wallet address', max_length=42)),
                ('block_number', models.PositiveIntegerField(blank=True, help_text='Block number containing the transaction', null=True)),
                ('confirmations', models.PositiveIntegerField(default=0, help_text='Number of block confirmations')),
                ('required_confirmations', models.PositiveIntegerField(default=12, help_text='Required confirmations for completion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current deposit status', max_length=20)),
                ('network_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Network transaction fee', max_digits=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When deposit was first detected')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When deposit was confirmed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When deposit was completed and credited', null=True)),
            ],
            options={
                'verbose_name': 'Wallet Deposit',
                'verbose_name_plural': 'Wallet Deposits',
                'db_table': 'payments_wallet_deposit',
            },
        ),
        migrations.CreateModel(
            name='WalletWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the withdrawal', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Withdrawal amount (excluding fees)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('withdrawal_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Withdrawal fee charged', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=8, help_text='Total amount (including fees)', max_digits=18)),
                ('to_address', models.CharField(help_text='Destination wallet address', max_length=42)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash (once processed)', max_length=66, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text='Current withdrawal status', max_length=20)),
                ('two_factor_verified', models.BooleanField(default=False, help_text='Whether 2FA was verified for this withdrawal')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether email verification was completed')),
                ('approval_code', models.CharField(blank=True, help_text='Email approval code', max_length=20)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=0, help_text='Gas price used for transaction', max_digits=15, null=True)),
                ('gas_used', models.PositiveIntegerField(blank=True, help_text='Gas used for transaction', null=True)),
                ('network_fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Network transaction fee paid', max_digits=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if withdrawal failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When withdrawal was approved', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When withdrawal was processed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When withdrawal was completed', null=True)),
            ],
            options={
                'verbose_name': 'Wallet Withdrawal',
                'verbose_name_plural': 'Wallet Withdrawals',
                'db_table': 'payments_wallet_withdrawal',
            },
        ),
        migrations.RemoveIndex(
            model_name='walletbalance',
            name='payments_wa_currenc_354653_idx',
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='contract_address',
            field=models.CharField(blank=True, help_text='Token contract address (for ERC-20 tokens)', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'Fiat Currency'), ('cryptocurrency', 'Cryptocurrency')], default='fiat', help_text='Type of currency (fiat or cryptocurrency)', max_length=20),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this currency is active for deposits/withdrawals'),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='minimum_withdrawal',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.01'), help_text='Minimum withdrawal amount for this currency', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))]),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='network',
            field=models.CharField(blank=True, help_text='Blockchain network (for cryptocurrencies)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Associated wallet address for cryptocurrency', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Fixed withdrawal fee for this currency', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='available_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Available balance for spending', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='currency',
            field=models.CharField(help_text='Currency code (USD, EUR, AED, BTC, ETH, MATIC, USDC, USDT, BNB)', max_length=10),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='locked_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Balance locked for pending transactions', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='walletbalance',
            name='pending_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Balance pending confirmation', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='walletbalance',
            index=models.Index(fields=['currency', 'currency_type'], name='payments_wa_currenc_861f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='walletbalance',
            index=models.Index(fields=['user', 'currency_type'], name='payments_wa_user_id_9ae8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='walletbalance',
            index=models.Index(fields=['is_active'], name='payments_wa_is_acti_941d06_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletbalance',
            constraint=models.CheckConstraint(check=models.Q(('available_balance__gte', 0)), name='wallet_available_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='walletbalance',
            constraint=models.CheckConstraint(check=models.Q(('pending_balance__gte', 0)), name='wallet_pending_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='walletbalance',
            constraint=models.CheckConstraint(check=models.Q(('locked_balance__gte', 0)), name='wallet_locked_balance_non_negative'),
        ),
        migrations.AddField(
            model_name='walletwithdrawal',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved withdrawal (if required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletwithdrawal',
            name='user',
            field=models.ForeignKey(help_text='User requesting withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletwithdrawal',
            name='wallet_balance',
            field=models.ForeignKey(help_text='Wallet balance being debited', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='payments.walletbalance'),
        ),
        migrations.AddField(
            model_name='walletdeposit',
            name='user',
            field=models.ForeignKey(help_text='User making the deposit', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletdeposit',
            name='wallet_balance',
            field=models.ForeignKey(help_text='Wallet balance being credited', on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='payments.walletbalance'),
        ),
        migrations.AddField(
            model_name='qrcodepayment',
            name='deposit',
            field=models.OneToOneField(blank=True, help_text='Associated deposit (if payment was made)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_payment', to='payments.walletdeposit'),
        ),
        migrations.AddField(
            model_name='qrcodepayment',
            name='user',
            field=models.ForeignKey(help_text='User requesting QR payment', on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrcodepayment',
            name='wallet_balance',
            field=models.ForeignKey(help_text='Target wallet balance', on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to='payments.walletbalance'),
        ),
        migrations.AddIndex(
            model_name='currencyexchangerate',
            index=models.Index(fields=['base_currency', 'target_currency'], name='payments_cu_base_cu_6df228_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyexchangerate',
            index=models.Index(fields=['last_updated'], name='payments_cu_last_up_81b689_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('base_currency', 'target_currency')},
        ),
        migrations.AddIndex(
            model_name='walletwithdrawal',
            index=models.Index(fields=['user', 'status'], name='payments_wa_user_id_d9ed0f_idx'),
        ),
        migrations.AddIndex(
            model_name='walletwithdrawal',
            index=models.Index(fields=['status', 'created_at'], name='payments_wa_status_8697e3_idx'),
        ),
        migrations.AddIndex(
            model_name='walletwithdrawal',
            index=models.Index(fields=['transaction_hash'], name='payments_wa_transac_2b642f_idx'),
        ),
        migrations.AddIndex(
            model_name='walletwithdrawal',
            index=models.Index(fields=['wallet_balance', 'status'], name='payments_wa_wallet__adb763_idx'),
        ),
        migrations.AddIndex(
            model_name='walletwithdrawal',
            index=models.Index(fields=['approved_by'], name='payments_wa_approve_0a71e0_idx'),
        ),
        migrations.AddIndex(
            model_name='walletdeposit',
            index=models.Index(fields=['user', 'status'], name='payments_wa_user_id_6dcbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='walletdeposit',
            index=models.Index(fields=['transaction_hash'], name='payments_wa_transac_dce1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='walletdeposit',
            index=models.Index(fields=['status', 'detected_at'], name='payments_wa_status_a8d142_idx'),
        ),
        migrations.AddIndex(
            model_name='walletdeposit',
            index=models.Index(fields=['wallet_balance', 'status'], name='payments_wa_wallet__11fd40_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodepayment',
            index=models.Index(fields=['user', 'status'], name='payments_qr_user_id_bd8cba_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodepayment',
            index=models.Index(fields=['wallet_address'], name='payments_qr_wallet__7820a2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodepayment',
            index=models.Index(fields=['status', 'expires_at'], name='payments_qr_status_cf6651_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodepayment',
            index=models.Index(fields=['created_at'], name='payments_qr_created_e719da_idx'),
        ),
    ]
