# Generated by Django 5.1.4 on 2025-09-16 13:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_currencyexchangerate_qrcodepayment_walletdeposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the bank transfer', primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(help_text='Name of the account holder', max_length=255)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=50)),
                ('routing_number', models.CharField(help_text='Bank routing number', max_length=50)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=255)),
                ('bank_address', models.TextField(blank=True, help_text='Bank address')),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT code for international transfers', max_length=20)),
                ('transfer_reference', models.CharField(help_text='Unique reference for the transfer', max_length=100, unique=True)),
                ('transfer_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', help_text='Current status of the bank transfer', max_length=20)),
                ('transfer_instructions', models.TextField(blank=True, help_text='Special instructions for the transfer')),
                ('estimated_completion_date', models.DateTimeField(blank=True, help_text='Estimated completion date for the transfer', null=True)),
                ('bank_reference_number', models.CharField(blank=True, help_text='Reference number provided by the bank', max_length=100)),
                ('verification_documents', models.JSONField(default=dict, help_text='Document IDs for verification')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Processing fee for the bank transfer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the transfer was completed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('payment', models.OneToOneField(help_text='Associated payment record', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'db_table': 'payments_bank_transfer',
                'indexes': [models.Index(fields=['payment', 'transfer_status'], name='payments_ba_payment_c519f0_idx'), models.Index(fields=['transfer_reference'], name='payments_ba_transfe_e6d520_idx'), models.Index(fields=['account_number'], name='payments_ba_account_50d689_idx'), models.Index(fields=['initiated_at'], name='payments_ba_initiat_628a7f_idx'), models.Index(fields=['transfer_status', 'estimated_completion_date'], name='payments_ba_transfe_5c2f11_idx')],
            },
        ),
    ]
