# Generated by Django 5.2.8 on 2025-12-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_nowpayments_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nowpaymentstransaction',
            new_name='payments_no_nowpaym_7fa77a_idx',
            old_name='payments_no_nowpaym_idx',
        ),
        migrations.RenameIndex(
            model_name='nowpaymentstransaction',
            new_name='payments_no_order_i_47507f_idx',
            old_name='payments_no_order_i_idx',
        ),
        migrations.RenameIndex(
            model_name='nowpaymentstransaction',
            new_name='payments_no_payment_c0a7dc_idx',
            old_name='payments_no_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='nowpaymentstransaction',
            new_name='payments_no_pay_cur_1136c1_idx',
            old_name='payments_no_pay_cur_idx',
        ),
        migrations.RenameIndex(
            model_name='nowpaymentstransaction',
            new_name='payments_no_created_32f862_idx',
            old_name='payments_no_created_idx',
        ),
    ]
