# Generated by Django 5.2.8 on 2026-02-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_payments_no_nowpaym_idx_payments_no_nowpaym_7fa77a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cryptocurrency', 'Cryptocurrency'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('wallet', 'Wallet')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cryptocurrency', 'Cryptocurrency'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('wallet', 'Wallet')], help_text='Type of payment method', max_length=20),
        ),
    ]
