# Generated by Django 6.0.5 on 2026-05-21 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_nova_sukuk_and_pronova'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='proof_of_transfer',
            field=models.FileField(blank=True, help_text='Proof of transfer (image or PDF) uploaded by the investor.', null=True, upload_to='bank_transfer_proofs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='review_note',
            field=models.TextField(blank=True, help_text='Admin-visible note explaining the approval / rejection.'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the admin reviewed the transfer.', null=True),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved / rejected this transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
