# Generated by Django 6.0.5 on 2026-05-21 15:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_banktransfer_proof_of_transfer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankWithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount (USD).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='IBAN / account number.', max_length=64)),
                ('routing_number', models.CharField(blank=True, max_length=64)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('bank_country', models.CharField(blank=True, help_text='ISO-3166 alpha-2.', max_length=2)),
                ('notes', models.TextField(blank=True, help_text='Free-form note from the investor.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Wire In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_withdrawal_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_bank_withdrawal_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_ba_user_id_53bd99_idx'), models.Index(fields=['status', 'created_at'], name='payments_ba_status_c9dc40_idx')],
            },
        ),
    ]
