# Generated by Django 6.0.5 on 2026-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_bankwithdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankwithdrawalrequest",
            name="crypto_address",
            field=models.CharField(
                blank=True, help_text="Destination wallet address.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="bankwithdrawalrequest",
            name="crypto_asset",
            field=models.CharField(
                blank=True,
                help_text="Payout asset, e.g. USDT, BTC, ETH.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bankwithdrawalrequest",
            name="crypto_memo",
            field=models.CharField(
                blank=True,
                help_text="Optional destination tag/memo for chains that require it.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="bankwithdrawalrequest",
            name="crypto_network",
            field=models.CharField(
                blank=True,
                help_text="Network/chain, e.g. BEP20, TRC20, ERC20, BTC, ETH.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="bankwithdrawalrequest",
            name="withdrawal_method",
            field=models.CharField(
                choices=[("bank", "Bank Transfer"), ("crypto", "Cryptocurrency")],
                db_index=True,
                default="bank",
                help_text="Destination type: bank wire or crypto payout.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bankwithdrawalrequest",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="bankwithdrawalrequest",
            name="account_number",
            field=models.CharField(
                blank=True, help_text="IBAN / account number.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="bankwithdrawalrequest",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
