# Generated by Django 4.2.7 on 2025-09-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
    ]
