# Generated by Django 4.2.7 on 2025-09-12 23:16

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0006_remove_installmentpayment_properties__propert_2f92c8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_auto_20250913_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the market listing', primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('sell', 'Sell Order'), ('buy', 'Buy Order')], help_text='Type of listing - sell or buy order', max_length=10)),
                ('tokens_offered', models.PositiveIntegerField(help_text='Number of tokens offered for sale or requested for purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('tokens_remaining', models.PositiveIntegerField(help_text='Number of tokens still available in this listing')),
                ('price_per_token', models.DecimalField(decimal_places=8, help_text='Price per token in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for all tokens in the listing', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_order_size', models.PositiveIntegerField(default=1, help_text='Minimum number of tokens per order', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_filled', 'Partially Filled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Current status of the listing', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When the listing expires')),
                ('auto_extend', models.BooleanField(default=False, help_text='Whether to automatically extend listing when it expires')),
                ('is_market_maker', models.BooleanField(default=False, help_text='Whether this listing is from a market maker')),
                ('priority_score', models.PositiveIntegerField(default=100, help_text='Priority score for order matching (higher = better)')),
                ('accepts_partial_fills', models.BooleanField(default=True, help_text='Whether to accept partial order fills')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the listing was completed', null=True)),
                ('property_listing', models.ForeignKey(help_text='Property associated with this listing', on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='properties.property')),
                ('seller', models.ForeignKey(help_text='User creating the listing', on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Listing',
                'verbose_name_plural': 'Market Listings',
                'db_table': 'marketplace_market_listing',
            },
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the trade order', primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order')], default='limit', help_text='Type of order - market or limit', max_length=10)),
                ('tokens_requested', models.PositiveIntegerField(help_text='Number of tokens requested in this order', validators=[django.core.validators.MinValueValidator(1)])),
                ('tokens_filled', models.PositiveIntegerField(default=0, help_text='Number of tokens actually filled')),
                ('price_per_token', models.DecimalField(decimal_places=8, help_text='Maximum price per token for buy orders', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), help_text='Platform fee percentage for this order', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('10.0000'))])),
                ('trading_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Trading fee amount calculated from total', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after fees', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the order', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the order was executed', null=True)),
                ('execution_price', models.DecimalField(blank=True, decimal_places=8, help_text='Actual execution price per token', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash for token transfer', max_length=255, null=True)),
                ('blockchain_confirmed', models.BooleanField(default=False, help_text='Whether blockchain transaction is confirmed')),
                ('confirmation_blocks', models.PositiveIntegerField(default=0, help_text='Number of blockchain confirmation blocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='User placing the order', on_delete=django.db.models.deletion.CASCADE, related_name='trade_orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Market listing this order is for', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.marketlisting')),
            ],
            options={
                'verbose_name': 'Trade Order',
                'verbose_name_plural': 'Trade Orders',
                'db_table': 'marketplace_trade_order',
            },
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the trade transaction', primary_key=True, serialize=False)),
                ('tokens_traded', models.PositiveIntegerField(help_text='Number of tokens traded', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_token', models.DecimalField(decimal_places=8, help_text='Price per token for this transaction', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount before fees', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('platform_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), help_text='Platform fee percentage applied', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('10.0000'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('buyer_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged to buyer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('seller_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged to seller', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount_to_seller', models.DecimalField(decimal_places=2, help_text='Net amount paid to seller after fees', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost_to_buyer', models.DecimalField(decimal_places=2, help_text='Total cost to buyer including fees', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_escrow', 'In Escrow'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the transaction', max_length=20)),
                ('payment_method', models.JSONField(default=dict, help_text='Payment method details')),
                ('blockchain_network', models.CharField(default='ethereum', help_text='Blockchain network used for token transfer', max_length=50)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255, null=True)),
                ('blockchain_confirmed', models.BooleanField(default=False, help_text='Whether blockchain transaction is confirmed')),
                ('confirmation_blocks', models.PositiveIntegerField(default=0, help_text='Number of blockchain confirmation blocks')),
                ('gas_fee', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), help_text='Gas fee for blockchain transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When payment processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transaction was completed', null=True)),
                ('market_cap_at_trade', models.DecimalField(blank=True, decimal_places=2, help_text='Property market cap at time of trade', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, help_text='24-hour trading volume at time of trade', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('buyer', models.ForeignKey(help_text='User who bought the tokens', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transactions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='Market listing involved in the trade', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.marketlisting')),
                ('order', models.ForeignKey(help_text='Trade order that resulted in this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.tradeorder')),
                ('property_traded', models.ForeignKey(help_text='Property whose tokens were traded', on_delete=django.db.models.deletion.CASCADE, related_name='trade_transactions', to='properties.property')),
                ('seller', models.ForeignKey(help_text='User who sold the tokens', on_delete=django.db.models.deletion.CASCADE, related_name='sale_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade Transaction',
                'verbose_name_plural': 'Trade Transactions',
                'db_table': 'marketplace_trade_transaction',
            },
        ),
        migrations.CreateModel(
            name='MarketAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for analytics record', primary_key=True, serialize=False)),
                ('timeframe', models.CharField(choices=[('1h', '1 Hour'), ('24h', '24 Hours'), ('7d', '7 Days'), ('30d', '30 Days'), ('90d', '90 Days'), ('1y', '1 Year'), ('all', 'All Time')], help_text='Time period for these analytics', max_length=5)),
                ('volume_tokens', models.PositiveIntegerField(default=0, help_text='Number of tokens traded')),
                ('volume_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD value of tokens traded', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('trade_count', models.PositiveIntegerField(default=0, help_text='Number of trades completed')),
                ('unique_traders', models.PositiveIntegerField(default=0, help_text='Number of unique traders')),
                ('opening_price', models.DecimalField(blank=True, decimal_places=8, help_text='Opening price for the period', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('closing_price', models.DecimalField(blank=True, decimal_places=8, help_text='Closing price for the period', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('high_price', models.DecimalField(blank=True, decimal_places=8, help_text='Highest price during the period', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('low_price', models.DecimalField(blank=True, decimal_places=8, help_text='Lowest price during the period', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, help_text='Volume-weighted average price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('active_listings_count', models.PositiveIntegerField(default=0, help_text='Number of active listings')),
                ('total_tokens_for_sale', models.PositiveIntegerField(default=0, help_text='Total tokens available for sale')),
                ('total_tokens_wanted', models.PositiveIntegerField(default=0, help_text='Total tokens wanted by buyers')),
                ('bid_ask_spread', models.DecimalField(blank=True, decimal_places=8, help_text='Spread between highest bid and lowest ask', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('new_listings_count', models.PositiveIntegerField(default=0, help_text='Number of new listings created')),
                ('completed_listings_count', models.PositiveIntegerField(default=0, help_text='Number of listings completed')),
                ('cancelled_listings_count', models.PositiveIntegerField(default=0, help_text='Number of listings cancelled')),
                ('platform_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform revenue from fees', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('period_start', models.DateTimeField(help_text='Start of the analytics period')),
                ('period_end', models.DateTimeField(help_text='End of the analytics period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_analyzed', models.ForeignKey(blank=True, help_text='Property these analytics are for (null for overall market)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_analytics', to='properties.property')),
            ],
            options={
                'verbose_name': 'Market Analytics',
                'verbose_name_plural': 'Market Analytics',
                'db_table': 'marketplace_market_analytics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the escrow account', primary_key=True, serialize=False)),
                ('amount_held', models.DecimalField(decimal_places=2, help_text='Amount held in escrow', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tokens_held', models.PositiveIntegerField(default=0, help_text='Number of tokens held in escrow')),
                ('status', models.CharField(choices=[('holding', 'Holding'), ('released', 'Released'), ('refunded', 'Refunded')], default='holding', help_text='Current status of the escrow', max_length=20)),
                ('escrow_wallet_address', models.CharField(blank=True, help_text='Escrow wallet address for holding tokens', max_length=255, null=True)),
                ('escrow_private_key_hash', models.CharField(blank=True, help_text='Hashed private key for escrow wallet', max_length=255, null=True)),
                ('timeout_duration', models.DurationField(default=datetime.timedelta(days=1), help_text='How long to hold funds in escrow before timeout')),
                ('timeout_at', models.DateTimeField(help_text='When escrow times out if not resolved')),
                ('buyer_approved', models.BooleanField(default=False, help_text='Whether buyer has approved the transaction')),
                ('seller_approved', models.BooleanField(default=False, help_text='Whether seller has approved the transaction')),
                ('admin_override', models.BooleanField(default=False, help_text='Whether admin has overridden normal release process')),
                ('resolution_reason', models.TextField(blank=True, help_text='Reason for escrow resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='When funds/tokens were released from escrow', null=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the escrow (admin or automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(help_text='Transaction this escrow account is for', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='marketplace.tradetransaction')),
            ],
            options={
                'verbose_name': 'Escrow Account',
                'verbose_name_plural': 'Escrow Accounts',
                'db_table': 'marketplace_escrow_account',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the trading pair', primary_key=True, serialize=False)),
                ('pair_type', models.CharField(choices=[('token_usd', 'Property Token / USD'), ('token_token', 'Property Token / Property Token'), ('token_crypto', 'Property Token / Cryptocurrency')], default='token_usd', help_text='Type of trading pair', max_length=15)),
                ('symbol', models.CharField(help_text='Trading pair symbol (e.g., PROP1/USD)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('delisted', 'Delisted')], default='active', help_text='Status of the trading pair', max_length=10)),
                ('minimum_order_size', models.PositiveIntegerField(default=1, help_text='Minimum order size in base tokens', validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_order_size', models.PositiveIntegerField(blank=True, help_text='Maximum order size in base tokens (null for unlimited)', null=True)),
                ('price_precision', models.PositiveIntegerField(default=8, help_text='Number of decimal places for price precision', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(18)])),
                ('quantity_precision', models.PositiveIntegerField(default=0, help_text='Number of decimal places for quantity precision', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Maker fee percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('10.0000'))])),
                ('taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), help_text='Taker fee percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('10.0000'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_property_pair', models.ForeignKey(help_text='Base property in the trading pair', on_delete=django.db.models.deletion.CASCADE, related_name='base_trading_pairs', to='properties.property')),
                ('quote_property_pair', models.ForeignKey(blank=True, help_text='Quote property in the trading pair (for token/token pairs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_trading_pairs', to='properties.property')),
            ],
            options={
                'verbose_name': 'Trading Pair',
                'verbose_name_plural': 'Trading Pairs',
                'db_table': 'marketplace_trading_pair',
                'indexes': [models.Index(fields=['status', 'pair_type'], name='marketplace_status_12c24c_idx'), models.Index(fields=['base_property_pair', 'status'], name='marketplace_base_pr_dbd92b_idx'), models.Index(fields=['symbol'], name='marketplace_symbol_2bdc26_idx'), models.Index(fields=['created_at'], name='marketplace_created_ef0854_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['buyer', 'completed_at'], name='marketplace_buyer_i_d79553_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['seller', 'completed_at'], name='marketplace_seller__5b248c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['property_traded', 'completed_at'], name='marketplace_propert_d11df7_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['status', 'created_at'], name='marketplace_status_f21326_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['price_per_token', 'completed_at'], name='marketplace_price_p_ecc703_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['transaction_hash'], name='marketplace_transac_c3ce88_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['completed_at'], name='marketplace_complet_6e6a23_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradetransaction',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gt', 0)), name='marketplace_transaction_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='tradetransaction',
            constraint=models.CheckConstraint(check=models.Q(('net_amount_to_seller__gte', 0)), name='marketplace_transaction_seller_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='tradetransaction',
            constraint=models.CheckConstraint(check=models.Q(('total_cost_to_buyer__gt', 0)), name='marketplace_transaction_buyer_cost_positive'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['listing', 'status'], name='marketplace_listing_989627_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['buyer', 'status'], name='marketplace_buyer_i_f63a38_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['price_per_token', 'order_type'], name='marketplace_price_p_e00d64_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['created_at'], name='marketplace_created_a65d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['executed_at'], name='marketplace_execute_43fe7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradeorder',
            constraint=models.CheckConstraint(check=models.Q(('tokens_filled__lte', models.F('tokens_requested'))), name='marketplace_order_tokens_filled_valid'),
        ),
        migrations.AddConstraint(
            model_name='tradeorder',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gt', 0)), name='marketplace_order_total_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['property_listing', 'listing_type', 'status'], name='marketplace_propert_fe44b3_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['seller', 'status'], name='marketplace_seller__098457_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['price_per_token', 'listing_type'], name='marketplace_price_p_37036d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['expires_at', 'status'], name='marketplace_expires_baf54f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['created_at'], name='marketplace_created_937b84_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['priority_score', 'price_per_token'], name='marketplace_priorit_8aca51_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(check=models.Q(('tokens_remaining__lte', models.F('tokens_offered'))), name='marketplace_tokens_remaining_valid'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(check=models.Q(('minimum_order_size__lte', models.F('tokens_offered'))), name='marketplace_minimum_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gt', 0)), name='marketplace_total_price_positive'),
        ),
        migrations.AddIndex(
            model_name='marketanalytics',
            index=models.Index(fields=['property_analyzed', 'timeframe', 'period_start'], name='marketplace_propert_94bdab_idx'),
        ),
        migrations.AddIndex(
            model_name='marketanalytics',
            index=models.Index(fields=['timeframe', 'period_start'], name='marketplace_timefra_d097ad_idx'),
        ),
        migrations.AddIndex(
            model_name='marketanalytics',
            index=models.Index(fields=['volume_usd', 'period_start'], name='marketplace_volume__460d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='marketanalytics',
            index=models.Index(fields=['created_at'], name='marketplace_created_af0d94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketanalytics',
            unique_together={('property_analyzed', 'timeframe', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['status', 'timeout_at'], name='marketplace_status_9d80aa_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['transaction'], name='marketplace_transac_2dc720_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['created_at'], name='marketplace_created_10b176_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['timeout_at'], name='marketplace_timeout_c13902_idx'),
        ),
        migrations.AddConstraint(
            model_name='escrowaccount',
            constraint=models.CheckConstraint(check=models.Q(('amount_held__gte', 0)), name='marketplace_escrow_amount_positive'),
        ),
    ]
